"""The single configuration file: its schema, its loader, its failure behaviour.

One file to edit, generated by ``mcgyvr init`` — not a short file. The
ladder is fully configurable, so sources, tier bindings, the orchestrator
and verifier roles, the sandbox, delivery and budgets all live here. It is
YAML rather than JSON because it carries policy, and policy needs comments
to stay hand-editable (ADR-0001, "Known tension").

Three properties are load-bearing and each is enforced here rather than
documented and hoped for:

1. **No silent defaults for things that must be bound.** A default ships
   only when it is a real working value. Anything else is absent, and its
   absence surfaces at the point of use naming the key and how to bind it —
   never as a fallback that makes a misconfiguration look like a bug.
2. **Unknown keys fail.** A typo'd key that is ignored is a config that
   silently does something other than what it says.
3. **Credentials are never values.** The config records only the NAME of
   the environment variable holding each key; the orchestrator process
   resolves it, and a task sandbox never sees it (see ``SECURITY.md``).

``SCHEMA`` below is declarative data, not a set of hand-written checks: it
is what the validator walks and what the config reference is generated
from, so a documented key and a validated key cannot drift apart.

This module only declares and loads. Detecting hardware, proposing
bindings, and writing the file are separate concerns and do not live here.
"""

from __future__ import annotations

import hashlib
import os
import re
import threading
import urllib.parse
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import yaml

SCHEMA_VERSION = 1
CONFIG_FILENAME = "mcgyvr.yaml"
CONFIG_PATH_ENV = "MCGYVR_CONFIG"
#: What a config's identity starts with (:meth:`Config.digest`), so it can
#: never be read as a product digest or a blob name: those are bare hex.
DIGEST_PREFIX = "cfg-"
#: Where the journal keeps the config each run was made under, by its digest
#: (:func:`keep`): ``<journal.dir>/configs/<digest>.yaml``. Naming that file
#: in ``MCGYVR_CONFIG`` re-selects the setup a result names, in one command.
CONFIGS_DIR = "configs"
#: The user-level config directory (owner, 2026-09-05). A literal with `~` so
#: help text reads the same on every machine; expanded at the point of use.
#: This is the third and last place a config is looked for, after the
#: environment override and the working directory, and where `mcgyvr init`
#: writes when nobody names a path. `$XDG_CONFIG_HOME` is not consulted.
USER_CONFIG_DIR = "~/.mcgyvr/config"


class ConfigError(Exception):
    """Base class for every configuration failure."""


class ConfigFileError(ConfigError):
    """The config file is missing, unreadable, or not parseable as YAML."""


class ConfigMissingError(ConfigFileError):
    """There is no config file at all.

    A class rather than a message to grep, because "there is none" and "the
    one that is there cannot be read" ask for different answers from a caller
    that can run without a config. The deterministic floor is one: it
    dispatches nothing, needs no ladder, and an install with no config is a
    supported install — so a missing file is silence, while a file the
    operator wrote and this run could not use is something to say out loud.

    Silence is the *default location's* to earn, not this class's. Whether the
    path was one the caller named is what :func:`named_config_path` answers,
    and a caller that treats this exception as "nothing to mention" has to ask:
    nobody chose the empty default, whereas ``--config`` or ``$MCGYVR_CONFIG``
    pointing at nothing is a path somebody typed, and a run that goes quietly
    on under some other directory is the operator's problem to discover later.
    """


class ConfigSchemaError(ConfigError):
    """The config parsed, but does not satisfy the schema."""


class CredentialInConfigError(ConfigSchemaError):
    """A credential was written into the config as a literal value.

    Distinct from a plain schema error because the remedy is not "fix the
    key" — the secret is now in a file that gets committed, and it has to be
    rotated.
    """


class UnboundValueError(ConfigError):
    """A value the running code needs is not bound.

    Raised at the point of use, never at load: a config that omits an API
    provider is valid, and only becomes a problem if something tries to use
    one.
    """


Kind = Literal[
    "int",
    "float",
    "str",
    "url",
    "bool",
    "enum",
    "env_name",
    "str_list",
    "block",
    "block_map",
    "block_list",
]


@dataclass(frozen=True)
class Field:
    """One key in the schema, with everything needed to validate and document it.

    ``doc`` has no default on purpose: a key that cannot be explained does
    not belong in a file a stranger is asked to edit.
    """

    name: str
    kind: Kind
    doc: str
    required: bool = False
    default: Any = None
    choices: tuple[str, ...] = ()
    block: tuple[Field, ...] = ()
    min_value: float | None = None
    bind_hint: str = ""

    retired: tuple[tuple[str, str], ...] = ()
    """Enum values this build recognises and refuses, each with why and what to
    set instead.

    Distinct from simply dropping the value out of ``choices``, which is what
    was tried first. That produces "not a valid value. Valid: ...", which is
    true and unhelpful: a value that used to work — and, in the one case here,
    used to be the *default* — was doing something other than what its name
    said, and an operator who wrote it deserves to be told which behaviour they
    were actually getting. A retired value is still recognised, so the message
    can be specific; it is refused, so the config cannot resolve to it."""


SOURCE_FIELDS: tuple[Field, ...] = (
    Field(
        "base_url",
        "url",
        "Where the source answers, including scheme and port.",
        required=True,
        bind_hint="e.g. http://localhost:11434",
    ),
    Field(
        "api",
        "enum",
        "Wire protocol. `openai` covers vLLM, llama-server, LM Studio and "
        "TGI, so adding a backend is a protocol question, not an "
        "integration.",
        required=True,
        choices=("ollama", "openai"),
    ),
    Field(
        "max_parallel",
        "int",
        "How many requests this source may run at once. Concurrency is "
        "capacity, not a preference: measured, three models ran concurrently "
        "on one card in 23.6 s against ~44 s serial.",
        default=1,
        min_value=1,
    ),
    Field(
        "api_key_env",
        "env_name",
        "NAME of the environment variable holding this source's key. Absent "
        "means the source needs no credential, which is the normal case for "
        "a local backend.",
        bind_hint=(
            "set it to the variable's NAME (e.g. ANTHROPIC_API_KEY), never "
            "the key itself"
        ),
    ),
    Field(
        "engine",
        "enum",
        "Which server program runs behind this URL, for `mcgyvr emit` to "
        "write a launch spec for. `api` cannot answer this: it is a wire "
        "protocol, and vLLM and llama-server both speak `openai` while "
        "taking entirely different argv. Absent means llama.cpp, which is "
        "what emit assumed unconditionally before this field existed. It "
        "belongs on the source rather than the rung because a URL points at "
        "one process and one process runs one engine.",
        choices=("llama.cpp", "vllm"),
        bind_hint="leave it out unless the backend is not llama-server",
    ),
    Field(
        "image",
        "str",
        "Container image `mcgyvr emit` writes for this source's process, as a "
        "tag or a digest. Absent means the engine's own default, and that is a "
        "floating tag: srv1's numbers are only valid against a stated build "
        "(okf/must-read/touching-rigs.md), so a source that must run one "
        "image says which here.",
        bind_hint="e.g. vllm/vllm-openai@sha256:<hex>, or llamacpp:b10644-L3",
    ),
)

MODEL_FIELDS: tuple[Field, ...] = (
    Field(
        "geometry_json",
        "str",
        "Path to this model's GGUF geometry: the `geometry.json` a serving-door "
        "run leaves in its envelope, or the output of `python -m "
        "mcgyvr.serving.ggufscan <gguf>` (a list; the row scanned from "
        "`<model>.gguf` is the one read). Once set it is the source of truth "
        "for the model's bytes — `disk_gb` is read from its `size_bytes`, and "
        "the card figure, the slot count and `--n-cpu-moe` are derived from "
        "its tensor table and cache geometry by the law in "
        "`mcgyvr.serving.vramfit`. A stated `disk_gb` that disagrees with it "
        "is refused, and so is a geometry scanned from a file this model does "
        "not serve: each deviation from a scan requires a new scan. Required "
        "for an MoE; a dense model without it is sized from `vram_gb` alone, "
        "one slot wide. A relative path is read against the config file's "
        "directory.",
        bind_hint=(
            "on a machine holding the file, `python -m mcgyvr.serving.ggufscan "
            "<gguf> > <model>.geometry.json`, and name that file here"
        ),
    ),
    Field(
        "vram_gb",
        "float",
        "Working set on the card with nothing offloaded, in GiB, for a dense "
        "model that has no `geometry_json`. Not the weight on disk: a working "
        "set carries buffers. Not read when `geometry_json` is set — the card "
        "figure is then derived from the header.",
        min_value=0.0,
        bind_hint=(
            "set it to what the server reports resident on the card with "
            "-ngl 99 and no offload, converted to GiB"
        ),
    ),
    Field(
        "disk_gb",
        "float",
        "Weight on disk, in GiB, for a model that has no `geometry_json`. "
        "Note the unit — a file listed as 13.2 GB by a tool using decimal "
        "gigabytes is 12.3 GiB here. Leave it out when `geometry_json` is set: "
        "it is then read from the scan's `size_bytes`, and a stated value that "
        "differs from that by more than rounding to two decimals is refused.",
        min_value=0.0,
        bind_hint="set it to `ls -l` on the weights file divided by 1024^3",
    ),
    Field(
        "ram_gb",
        "float",
        "A floor on what system memory may be asked to hold, in GiB. Absent "
        "means the offload arithmetic decides it alone; state it only to "
        "claim a demand this module cannot see.",
        default=0.0,
        min_value=0.0,
    ),
    Field(
        "moe",
        "bool",
        "Whether this model has expert weights that `--n-cpu-moe` can move "
        "off the card. Not inferable from the other numbers: it is the "
        "difference between `does not fit` and `fits differently here`.",
        default=False,
    ),
    Field(
        "hf_cache",
        "str",
        "The HuggingFace cache on the rig that holds this model's weights, as "
        "an absolute path there. Required for a model served by vLLM, which "
        "loads a repository id from that cache rather than a file from the "
        "weights directory; `mcgyvr emit` mounts it read-only and starts the "
        "server offline, so nothing is downloaded on a rig at load. Not read "
        "for a llama.cpp model.",
        bind_hint="e.g. /home/<user>/.cache/huggingface, as the rig sees it",
    ),
    Field(
        "serve_args",
        "str_list",
        "Arguments appended verbatim to the server's command line after the "
        "ones mcgyvr derives, for what no scan can know: `--gpu-memory-"
        "utilization` for vLLM (measured per rig, #337, never inherited), or "
        "`--chat-template-kwargs` to turn a thinking model's reasoning off. "
        "One flag or value per entry; an entry containing whitespace is "
        "refused at emit, because the compose file and the pasted command "
        "cannot spell it the same way.",
        default=(),
    ),
)

TIER_FIELDS: tuple[Field, ...] = (
    Field(
        "name",
        "str",
        "How this rung is referred to elsewhere — risk floors, routing "
        "policy, telemetry. Conventionally `<locality>_<model>`, e.g. "
        "`local_qwen2.5-coder-7b`, which says what the rung is rather than "
        "where it sits: a positional name silently changes meaning when a "
        "rung is inserted above it. There is no role in the name because a "
        "binding's role is already given by where it sits — this is the "
        "ladder, so it is a worker.",
        required=True,
    ),
    Field(
        "source",
        "str",
        "Which declared source executes this rung. Resolution happens at the "
        "execution seam only — nothing above it knows where work ran.",
        required=True,
    ),
    Field("model", "str", "Model identifier as the source names it.", required=True),
    Field(
        "max_parallel",
        "int",
        "How many requests this rung may run at once, overriding its source's "
        "`max_parallel`. Concurrency is a property of the serving process "
        "rather than of the machine: the same weights on two rigs are two "
        "processes started with two different slot counts, so one number on "
        "the source cannot describe both. Unset means the source's number "
        "stands, which is what it has always meant.",
        min_value=1,
        bind_hint=(
            "set it to the slot count the rung's backend was started with "
            "(e.g. 8), and leave it out to inherit the source's"
        ),
    ),
    Field(
        "attempts",
        "int",
        "How many times this rung may be tried before escalation moves on. "
        "The default of 1 is escalate-rather-than-retry: a second attempt "
        "re-runs the same model on the same input, and the figure inherited "
        "from local-ai and not re-verified here (#152) — worker-tier "
        "remediation rescued 2 of 35 failures — says that is usually spend "
        "without a result. Raising it is most "
        "defensible on the dearest rung, which has nowhere to escalate to. A "
        "contract's `limits.attempts` caps this per task; the lower of the "
        "two applies.",
        default=1,
        min_value=1,
    ),
)

LADDER_FIELDS: tuple[Field, ...] = (
    Field(
        "tiers",
        "block_list",
        "The rungs, cheapest first. A higher rung must be measurably better "
        "than the one below or it is not a rung — binding a faster-but-weaker "
        "model above a slower-but-stronger one inverts the ladder and makes "
        "escalation actively harmful.",
        required=True,
        block=TIER_FIELDS,
    ),
    Field(
        "fanout",
        "enum",
        "Whether a batch of contracts spreads across rungs or queues on one. "
        "`none` is today's behaviour: the cheapest rung at or above the "
        "contract's floor, queued behind whoever is already there. `full` "
        "starts each climb on the cheapest rung that has a free slot, so a "
        "batch fills every rig that can serve it instead of stacking on one — "
        "and it never leaves the contract's floor family, so it cannot spend. "
        "`idle` uses that same rule and then lifts the one limit: the floor is "
        "the only bound and nothing bounds it above, so when every rung of "
        "every cheaper family is full it enters a priced api family rather "
        "than wait. That is the difference between the two, and it is a spend "
        "decision the knob makes deliberately. Neither mode reorders the "
        "ladder: load decides which rung a climb starts on and never what it "
        "may spend, so a rung passed over for being full is still walked, and "
        "a rung that can run now is never passed over for a dearer one with "
        "more room. It is a knob rather than a behaviour because the right "
        "answer is a property of the machines: two interchangeable rigs "
        "should share a batch, but a throughput rig feeding an intelligence "
        "rig must not — the second is sized to drain the first's failure "
        "tail, and fanning volume onto it eats exactly the capacity that "
        "drain needs.",
        default="none",
        choices=("none", "idle", "full"),
    ),
)

ROLE_FIELDS: tuple[Field, ...] = (
    Field(
        "source",
        "str",
        "Which declared source serves this role. Unset until something needs the role.",
        bind_hint="name one of the sources declared under `sources`",
    ),
    Field(
        "model",
        "str",
        "Model identifier as that source names it.",
        bind_hint="name a model the bound source can serve",
    ),
)

VERIFIER_FIELDS: tuple[Field, ...] = (
    Field(
        "enabled",
        "bool",
        "Model verification of the applied diff, on top of the gate. Off by "
        "default because the deterministic gate is the acceptance bar and a "
        "keyless install is a supported configuration, not a degraded one.",
        default=False,
    ),
    *ROLE_FIELDS,
)

SANDBOX_FIELDS: tuple[Field, ...] = (
    Field(
        "mode",
        "enum",
        "`docker` runs each task in its own container, torn down after. "
        "`tempdir` is the explicitly weaker fallback for installs without "
        "Docker: acceptance commands are arbitrary shell from a contract, "
        "running on someone else's machine.",
        default="docker",
        choices=("docker", "tempdir"),
    ),
    Field(
        "image",
        "str",
        "Base image for task containers. Unset means detect the repository's "
        "stack and build one.",
        bind_hint="name an image tag, or leave unset to let the stack be detected",
    ),
    Field(
        "setup",
        "str_list",
        "Commands run once when the task image is built, before any task.",
        default=(),
    ),
)

DELIVERY_FIELDS: tuple[Field, ...] = (
    Field(
        "mode",
        "enum",
        "Where an accepted change is committed. `branch` puts it on a new "
        "local branch named after the contract and leaves the branch you have "
        "checked out, your index and your working tree exactly as they were — "
        "the delivery tells you the `git push` to run. `none` commits onto the "
        "branch you have checked out. Nothing here pushes or opens a pull "
        "request: mcgyvr reaches your repository through `git` and has no "
        "forge, so the last step off this machine is yours.",
        default="branch",
        choices=("branch", "none"),
        retired=(
            (
                "pull_request",
                "is no longer a mode. It never opened one — every mode "
                "committed straight to your checked-out branch, and the pull "
                "request was recorded as owed to something that does not "
                "exist. Opening one needs a forge and a credential this build "
                "has nowhere to put. Set `branch` for a commit on a branch of "
                "its own plus the push to run, or `none` to commit onto the "
                "branch you have checked out.",
            ),
        ),
    ),
)

#: Where the live journal goes when `journal.dir` is left out. A literal with
#: `~` rather than an expanded path so the reference reads the same on every
#: machine; expanded at the point of use. The XDG state dir is the convention
#: `mcgyvr scan` already keeps its records under.
JOURNAL_DIR_DEFAULT = "~/.local/state/mcgyvr/journal"

JOURNAL_FIELDS: tuple[Field, ...] = (
    Field(
        "dir",
        "str",
        "Where every run journals what it asked, what came back and how it "
        "landed: one `<orchestrator>.jsonl` per writer, the prompts and replies "
        "content-addressed under `blobs/`, and each run's result file under "
        "`results/`. Deterministic runs are here too, with a row naming the "
        "program instead of a model. This is mcgyvr's own record, it never "
        "lands in the repository a run works on, and nothing on the command "
        "line moves it: it is the one place every run is, which is what makes "
        "it worth asking questions of. `mcgyvr run --record DIR` adds a second "
        "copy for your own use. Read either back with `tools/live/review.py "
        "DIR`. The config each run was made under is kept here too, as "
        "`configs/<digest>.yaml`, and every row and result names that "
        "digest: `MCGYVR_CONFIG=<dir>/configs/<digest>.yaml` re-selects the "
        "exact setup a result was produced under.",
        default=JOURNAL_DIR_DEFAULT,
    ),
)

BUDGET_FIELDS: tuple[Field, ...] = (
    Field(
        "max_escalations",
        "int",
        "How many rungs a task may climb before it is handed back unfinished. "
        "A cheap rung that fails and escalates costs more than starting "
        "higher, so this is a real ceiling, not a retry count.",
        default=1,
        min_value=0,
    ),
    Field(
        "max_attempts",
        "int",
        "Hard ceiling on how many attempts one task may spend in total, "
        "across every rung and every family it climbs. Unset means the "
        "ladder's own budget bounds it — the sum of each reachable rung's "
        "`attempts`, which `mcgyvr pool` prints — so leaving it unset is not "
        "unbounded. Set it when you have raised a rung's `attempts` or "
        "`max_escalations` and want one number that still holds. A decline "
        "costs nothing against it: a rung that stepped aside spent no attempt.",
        min_value=1,
        bind_hint=(
            "set a whole number of attempts, or leave it unset to be bounded "
            "by the ladder's own budget (`mcgyvr pool` prints that number)"
        ),
    ),
    Field(
        "task_timeout_s",
        "int",
        "Wall-clock ceiling for one task, including acceptance commands.",
        default=900,
        min_value=1,
    ),
)

BREADTH_FIELDS: tuple[Field, ...] = (
    Field(
        "draws",
        "int",
        "How many candidates one attempt asks its rung for before the gate "
        "picks between them. Draws are not attempts: they share one prompt and "
        "one attempt's budget, and the gate ranks the answers rather than the "
        "next attempt being told what the last one got wrong. The default of 1 "
        "is ADR-0008 unchanged — one draw, one verdict, and the draw is the "
        "answer. Raising it is most defensible on a cheap rung that is often "
        "almost right, where three draws are still cheaper than escalating; a "
        "lever whose whole benefit is fewer crossings into the api family "
        "cannot be evaluated before the telemetry that counts crossings, which "
        "is why this is something to ask for rather than something you are "
        "given.",
        default=1,
        min_value=1,
    ),
)

CLEANUP_FIELDS: tuple[Field, ...] = (
    Field(
        "enabled",
        "bool",
        "Repair a change the gate rejected with the deterministic tools — the "
        "declared imports, the linter's own autofixes, the formatter — and "
        "judge it again on the same rung, instead of spending an attempt or a "
        "climb on what a tool clears for nothing. The tools are the ones the "
        "gate already checks with, so a repair produces the shape the rungs "
        "ask for rather than a second opinion about it, and it costs no tokens "
        "by construction. On by default (owner, 2026-09-05): the first live "
        "ladder rejected all nine replies on a reflowed line, whitespace on a "
        "blank line or an unsorted import block and paid a climb for each, "
        "and running the fixers after a rung is done is the point — it lifts "
        "every task the deterministic floor could not take outright. It "
        "rewrites a file after the gate has spoken about it, so the bytes "
        "that come back are not the bytes the worker sent: the journal keeps "
        "the reply, the tree keeps the repaired file, and the verdict says a "
        "repair ran. Set false to have the rejection stand as the gate "
        "reached it. What no tool fixes — a failed acceptance command, a "
        "name, a line too long to wrap — is rejected exactly as before.",
        default=True,
    ),
)

SCHEMA: tuple[Field, ...] = (
    Field(
        "version",
        "int",
        f"Config schema version. Currently {SCHEMA_VERSION}; bumped only by a "
        "breaking change to this file's shape.",
        required=True,
        min_value=1,
    ),
    Field(
        "profile",
        "enum",
        "Which setup this file is: `live`, the ladder that serves for real, or "
        "`dev`, a setup under development. The default is `live`, because the "
        "safe value is the one you get when you say nothing: "
        "`~/.mcgyvr/config/mcgyvr.yaml` is the unnamed fallback and is the "
        "live setup, and a dev setup is a file you name in `MCGYVR_CONFIG` "
        "(or a `mcgyvr.yaml` beside the work), so forgetting the variable "
        "lands on the live setup and never the other way round. Live outranks "
        "dev on the rigs: a run under a `dev` profile does not start or stop "
        "the live ladder.",
        choices=("live", "dev"),
        default="live",
    ),
    Field(
        "sources",
        "block_map",
        "Where model work is executed, keyed by a name you choose. A source "
        "is an endpoint with a capacity and a wire protocol — nothing above "
        "the execution seam knows which host or backend served a request.",
        required=True,
        block=SOURCE_FIELDS,
    ),
    Field(
        "models",
        "block_map",
        "Serving specs for models the shipped capability table does not "
        "carry, or whose numbers you want to override, keyed by the model "
        "identifier a rung names. mcgyvr sizes from what it can measure; this "
        "is where an operator states what it cannot. A declaration here wins "
        "over the table and is not second-guessed — a wrong one produces a "
        "launch spec that fails on the rig, which is the operator's to make.",
        block=MODEL_FIELDS,
    ),
    Field(
        "ladder",
        "block",
        "The rungs work climbs, and what each is bound to.",
        required=True,
        block=LADDER_FIELDS,
    ),
    Field(
        "orchestrator",
        "block",
        "The role that turns a prompt plus a repository into contracts. Only "
        "used in delegated mode; direct mode authors contracts itself.",
        block=ROLE_FIELDS,
    ),
    Field(
        "verifier",
        "block",
        "The role that reads an applied diff in fresh context.",
        block=VERIFIER_FIELDS,
    ),
    Field("sandbox", "block", "Where a task's commands run.", block=SANDBOX_FIELDS),
    Field(
        "delivery",
        "block",
        "How accepted work gets back to you.",
        block=DELIVERY_FIELDS,
    ),
    Field(
        "budgets",
        "block",
        "The ceilings that bound one task's cost.",
        block=BUDGET_FIELDS,
    ),
    Field(
        "breadth",
        "block",
        "How many answers one attempt asks for. Separate from `budgets` "
        "because breadth is not a ceiling: it is what a single attempt spends, "
        "and every budget in this file still counts that attempt once.",
        block=BREADTH_FIELDS,
    ),
    Field(
        "cleanup",
        "block",
        "What may be fixed without asking a model.",
        block=CLEANUP_FIELDS,
    ),
    Field(
        "journal",
        "block",
        "Where mcgyvr keeps its own record of what it dispatched.",
        block=JOURNAL_FIELDS,
    ),
)


# Keys that would hold a credential as a value. They are unknown keys and
# would be rejected anyway, but the generic "unknown key" message is the
# wrong advice: what matters is that a secret must not be written here at
# all.
_CREDENTIAL_KEYS = frozenset(
    {
        "access_key",
        "api_key",
        "apikey",
        "auth",
        "auth_token",
        "credential",
        "credentials",
        "key",
        "passwd",
        "password",
        "private_key",
        "secret",
        "secret_key",
        "token",
    }
)

# High-signal credential shapes. This is a tripwire for the obvious cases,
# not a secret scanner — the schema is what actually keeps keys out, by
# giving them nowhere to go.
_CREDENTIAL_VALUE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^sk-[A-Za-z0-9_\-]{16,}$"),
    re.compile(r"^(ghp|gho|ghs|ghu|ghr)_[A-Za-z0-9]{20,}$"),
    re.compile(r"^github_pat_[A-Za-z0-9_]{20,}$"),
    re.compile(r"^AKIA[0-9A-Z]{16}$"),
    re.compile(r"^xox[baprs]-[A-Za-z0-9\-]{10,}$"),
    re.compile(r"^AIza[0-9A-Za-z_\-]{30,}$"),
)

_ENV_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass(frozen=True)
class Source:
    """One endpoint work can be dispatched to."""

    name: str
    base_url: str
    api: str
    max_parallel: int
    api_key_env: str | None
    engine: str | None = None
    image: str | None = None

    @property
    def requires_credential(self) -> bool:
        return self.api_key_env is not None


@dataclass(frozen=True)
class Tier:
    """One rung of the ladder, bound to a source and a model.

    ``attempts`` is routing policy rather than a property of the binding: it is
    how many times this rung is tried before escalation leaves it, and it lives
    here because policy references a rung by name (ADR-0008). It defaults to 1
    so that the configured behaviour is to escalate rather than retry.

    ``max_parallel`` is ``None`` rather than a number when the rung does not
    state one, because "this rung was started with eight slots" and "nobody
    said, so the source's number stands" are different facts and a rung that
    defaulted to the source's value would be indistinguishable from a rung that
    declared it. :meth:`mcgyvr.capacity.Capacity.limit` is where the fallback
    happens, once, at the point the bound is actually built.
    """

    name: str
    source: str
    model: str
    max_parallel: int | None = None
    attempts: int = 1


@dataclass(frozen=True)
class Ladder:
    tiers: tuple[Tier, ...]
    fanout: str = "none"

    def get(self, name: str) -> Tier | None:
        return next((t for t in self.tiers if t.name == name), None)


@dataclass(frozen=True)
class Config:
    """A loaded, validated configuration.

    ``data`` is the validated tree with defaults filled in; ``sources`` and
    ``ladder`` are typed views over the parts that are fully determined.
    Values that are legitimately optional are reached through ``require``
    and ``secret``, which fail at the point of use rather than at load.
    """

    path: Path | None
    data: Mapping[str, Any]
    sources: Mapping[str, Source]
    ladder: Ladder

    @property
    def is_local_only(self) -> bool:
        """Whether every rung runs on a source needing no credential."""
        return not any(
            self.sources[t.source].requires_credential for t in self.ladder.tiers
        )

    def get(self, key: str, default: Any = None) -> Any:
        """Read a dotted key, or ``default`` when it is unbound."""
        try:
            return _dig(self.data, key)
        except KeyError:
            return default

    def require(self, key: str) -> Any:
        """Read a dotted key, failing loud by name when it is not bound.

        This is the point of use. The error names the key and says how to
        bind it, because the alternative — a plausible default — turns a
        misconfiguration into a bug report about something else.
        """
        try:
            value = _dig(self.data, key)
        except KeyError as exc:
            raise UnboundValueError(self._unbound(key)) from exc
        if value is None or value == "" or value == () or value == []:
            raise UnboundValueError(self._unbound(key))
        return value

    def secret(self, key: str) -> str:
        """Resolve the credential whose variable NAME is bound at ``key``.

        Two distinct failures, kept distinct: the config does not say which
        variable holds the key, or it does and that variable is not set.
        """
        var = self.require(key)
        value = os.environ.get(str(var))
        if not value:
            raise UnboundValueError(
                f"environment variable {var} is not set — it is named by "
                f"`{key}`{self._in_file()}. Export it in your shell or put it "
                f"in a git-ignored .env; never write the value into the "
                f"config file."
            )
        return value

    def canonical(self) -> str:
        """The loaded config as one YAML text, the same for every spelling of it.

        Keys sorted, no anchors or aliases, block style throughout, and every
        default the loader filled in written out: two files that load to the
        same config render to the same bytes, whatever their comments, blank
        lines or key order, and a file that omits a defaulted key renders as
        one that states it. What is NOT in it is where the file sat —
        ``path`` is a fact about the caller, not the config — except through
        the one key whose meaning depends on it: a relative ``geometry_json``
        is read beside the config (:func:`mcgyvr.serving.units_for`), so it
        is written here as the file it names, absolutely. Two copies of a
        config that name different geometry files are two setups, and a kept
        copy that pointed beside itself would re-select a geometry that is
        not there. Loading this text back yields the same config, and the
        same digest.
        """
        return yaml.dump(
            _plain(self._pinned()),
            Dumper=_CanonicalDumper,
            sort_keys=True,
            default_flow_style=False,
            allow_unicode=True,
            width=1_000_000,
        )

    def _pinned(self) -> Mapping[str, Any]:
        """``data`` with every path-valued key made absolute, as it is used."""
        models = self.data.get("models")
        if not isinstance(models, Mapping) or self.path is None:
            return self.data
        pinned: dict[str, Any] = {}
        for name, block in models.items():
            stated = block.get("geometry_json") if isinstance(block, Mapping) else None
            if not stated:
                pinned[name] = block
                continue
            where = Path(str(stated)).expanduser()
            if not where.is_absolute():
                where = self.path.parent / where
            pinned[name] = {**block, "geometry_json": str(where)}
        return {**self.data, "models": pinned}

    def digest(self) -> str:
        """The config's identity: ``cfg-`` and the sha256 of :meth:`canonical`.

        Over the loaded and validated tree and never over the file's bytes,
        because an identity that moved when a comment was added would name
        the edit and not the setup (owner's ruling R2, 2026-09-06).
        """
        raw = self.canonical().encode("utf-8")
        return DIGEST_PREFIX + hashlib.sha256(raw).hexdigest()

    def _unbound(self, key: str) -> str:
        field = field_at(key)
        parts = [f"`{key}` is not bound{self._in_file()}."]
        if field is not None:
            parts.append(field.doc)
            if field.bind_hint:
                parts.append(f"To bind it: {field.bind_hint}.")
        return " ".join(parts)

    def _in_file(self) -> str:
        return f" in {self.path}" if self.path is not None else ""


class _CanonicalDumper(yaml.SafeDumper):
    """A SafeDumper that never writes an anchor.

    Two keys sharing one default object — a tuple declared once in the
    schema — would otherwise render as ``&id001`` and ``*id001``, and the
    digest would depend on object identity inside this process.
    """

    def ignore_aliases(self, data: object) -> bool:
        return True


def _plain(value: Any) -> Any:
    """``value`` as plain dicts, lists and scalars, for a canonical dump."""
    if isinstance(value, Mapping):
        return {str(k): _plain(v) for k, v in value.items()}
    if isinstance(value, Sequence) and not isinstance(value, str | bytes):
        return [_plain(v) for v in value]
    if isinstance(value, Path):
        return str(value)
    return value


def keep(config: Config, journal_dir: Path) -> Path:
    """File ``config`` under ``journal_dir`` by its digest, and return the path.

    ``<journal_dir>/configs/<digest>.yaml``, holding :meth:`Config.canonical`:
    the one place a result's ``config_digest`` can be followed back to, and
    the file to name in ``MCGYVR_CONFIG`` to run under exactly that setup
    again. Content-addressed, so one that is already there and reads as the
    text it should hold is left alone; one that reads otherwise — a copy a
    crash left short — is replaced, because a kept copy that will not load
    is worse than none. A new one is staged under a name unique to this
    writer, opened exclusively, and moved into place whole, as the journal's
    blobs are: two runs keeping the same config at once each stage their
    own, and the last move wins with bytes identical to the first. An
    ``OSError`` propagates: a copy that cannot be written is a result that
    cannot be traced, and the caller says so.
    """
    text = config.canonical()
    where = journal_dir / CONFIGS_DIR
    path = where / f"{config.digest()}.yaml"
    try:
        if path.read_text(encoding="utf-8") == text:
            return path
    except (OSError, UnicodeDecodeError):
        pass
    where.mkdir(parents=True, exist_ok=True)
    staging = where / f".{path.name}.{os.getpid()}-{threading.get_ident()}.part"
    fd = os.open(staging, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o644)
    try:
        try:
            data = text.encode("utf-8")
            while data:
                data = data[os.write(fd, data) :]
        finally:
            os.close(fd)
        os.replace(staging, path)
    except BaseException:
        staging.unlink(missing_ok=True)
        raise
    return path


def field_at(key: str) -> Field | None:
    """Find the schema field a dotted key addresses, if it names one.

    Segments that are a user-chosen map key or a list index are skipped —
    ``sources.local.api_key_env`` and ``ladder.tiers.0.model`` both resolve.
    """
    fields = SCHEMA
    parts = key.split(".")
    index = 0
    while index < len(parts):
        found = next((f for f in fields if f.name == parts[index]), None)
        if found is None:
            return None
        index += 1
        if found.kind == "block":
            fields = found.block
        elif found.kind in ("block_map", "block_list"):
            index += 1  # the caller-chosen name or index
            fields = found.block
        else:
            return found if index == len(parts) else None
        if index == len(parts):
            return found
    return None


def _dig(data: Mapping[str, Any], key: str) -> Any:
    current: Any = data
    for part in key.split("."):
        if isinstance(current, Mapping) and part in current:
            current = current[part]
        elif isinstance(current, Sequence) and not isinstance(current, str):
            try:
                current = current[int(part)]
            except (ValueError, IndexError) as exc:
                raise KeyError(key) from exc
        else:
            raise KeyError(key)
    return current


class _StrictLoader(yaml.SafeLoader):
    """SafeLoader that refuses duplicate keys instead of taking the last one."""


def _no_duplicate_keys(
    loader: yaml.SafeLoader, node: yaml.nodes.MappingNode
) -> dict[Any, Any]:
    mapping: dict[Any, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=True)
        try:
            hash(key)
        except TypeError:
            # `[dev]: x` — a list as a key. YAML allows it; a config does
            # not, and `key in mapping` would have raised a TypeError past
            # every caller expecting a ConfigError.
            mark = key_node.start_mark
            raise ConfigSchemaError(
                f"key {key!r} at line {mark.line + 1} is not a plain name; a "
                "config key is one word, never a list or a mapping."
            ) from None
        if key in mapping:
            mark = key_node.start_mark
            raise ConfigSchemaError(
                f"duplicate key {key!r} at line {mark.line + 1} — YAML would "
                f"silently keep only the last one, so the file does not mean "
                f"what it looks like it means."
            )
        mapping[key] = loader.construct_object(value_node, deep=True)
    return mapping


_StrictLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _no_duplicate_keys
)


def _typename(value: object) -> str:
    if value is None:
        return "nothing"
    return {
        bool: "a true/false value",
        int: "a number",
        float: "a number",
        str: "text",
        list: "a list",
        dict: "a block of keys",
    }.get(type(value), type(value).__name__)


def _join(path: str, name: str) -> str:
    return f"{path}.{name}" if path else name


def _reject_credential_literal(value: str, path: str) -> None:
    if any(p.match(value) for p in _CREDENTIAL_VALUE_PATTERNS):
        raise CredentialInConfigError(
            f"{path}: this looks like a credential written into the config. "
            f"Credentials are never values here — the config records only the "
            f"NAME of the environment variable holding a key. Rotate this "
            f"secret, then bind it by name."
        )


def _reject_credential_key(name: str, path: str) -> None:
    if name.lower() in _CREDENTIAL_KEYS:
        raise CredentialInConfigError(
            f"{_join(path, name)}: a credential cannot be expressed in the "
            f"config. Name the environment variable that holds it instead "
            f"(`api_key_env` on a source), and keep "
            f"the value in your environment."
        )


def _mapping(raw: object, path: str) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise ConfigSchemaError(
            f"{path or 'config'}: expected a block of keys, found {_typename(raw)}"
        )
    for key in raw:
        if not isinstance(key, str):
            raise ConfigSchemaError(
                f"{path or 'config'}: key {key!r} is not text — keys must be names"
            )
    return dict(raw)


def _default_for(spec: Field) -> Any:
    if spec.kind == "block":
        return _block({}, spec.block, "")
    if spec.kind == "block_map":
        return {}
    if spec.kind == "block_list":
        return []
    if spec.kind == "str_list":
        return list(spec.default or ())
    return spec.default


def _missing(spec: Field, path: str) -> ConfigSchemaError:
    parts = [f"{path}: required key is not set.", spec.doc]
    if spec.bind_hint:
        parts.append(f"To bind it: {spec.bind_hint}.")
    return ConfigSchemaError(" ".join(parts))


def _value(raw: object, spec: Field, path: str) -> Any:
    if spec.kind == "int":
        # bool is an int in Python; `max_parallel: true` is not a capacity.
        if not isinstance(raw, int) or isinstance(raw, bool):
            raise ConfigSchemaError(
                f"{path}: expected a number, found {_typename(raw)}"
            )
        if spec.min_value is not None and raw < spec.min_value:
            raise ConfigSchemaError(
                f"{path}: must be at least {spec.min_value}, found {raw}"
            )
        return raw

    if spec.kind == "float":
        # An int is a valid decimal, but a bool is not: `moe: true` and
        # `disk_gb: true` must not both be accepted by the same rule.
        if not isinstance(raw, (int, float)) or isinstance(raw, bool):
            raise ConfigSchemaError(
                f"{path}: expected a number, found {_typename(raw)}"
            )
        if spec.min_value is not None and raw < spec.min_value:
            raise ConfigSchemaError(
                f"{path}: must be at least {spec.min_value}, found {raw}"
            )
        return float(raw)

    if spec.kind == "bool":
        if not isinstance(raw, bool):
            raise ConfigSchemaError(
                f"{path}: expected true or false, found {_typename(raw)}"
            )
        return raw

    if spec.kind in ("str", "url", "enum", "env_name"):
        if not isinstance(raw, str):
            raise ConfigSchemaError(f"{path}: expected text, found {_typename(raw)}")
        value = raw.strip()
        if not value:
            raise ConfigSchemaError(
                f"{path}: is empty. Remove the key or give it a value — an "
                f"empty value is not the same as an unset one."
            )
        _reject_credential_literal(value, path)
        if spec.kind == "enum":
            for name, why in spec.retired:
                if value == name:
                    raise ConfigSchemaError(f"{path}: `{value}` {why}")
            if value not in spec.choices:
                raise ConfigSchemaError(
                    f"{path}: {value!r} is not a valid value. Valid: "
                    f"{', '.join(spec.choices)}"
                )
        if spec.kind == "url" and not value.startswith(("http://", "https://")):
            raise ConfigSchemaError(
                f"{path}: {value!r} is not a URL — it needs a scheme, e.g. "
                f"http://{value}"
            )
        if spec.kind == "env_name" and not _ENV_NAME.match(value):
            raise ConfigSchemaError(
                f"{path}: {value!r} is not an environment variable name. This "
                f"key takes the NAME of the variable holding the value (e.g. "
                f"ANTHROPIC_API_KEY), never the value itself."
            )
        return value

    if spec.kind == "str_list":
        if not isinstance(raw, list):
            raise ConfigSchemaError(f"{path}: expected a list, found {_typename(raw)}")
        out: list[str] = []
        for i, item in enumerate(raw):
            if not isinstance(item, str) or not item.strip():
                raise ConfigSchemaError(
                    f"{path}.{i}: expected text, found {_typename(item)}"
                )
            _reject_credential_literal(item.strip(), f"{path}.{i}")
            out.append(item.strip())
        return out

    if spec.kind == "block":
        return _block(raw, spec.block, path)

    if spec.kind == "block_map":
        given = _mapping(raw, path)
        return {
            name: _block(item, spec.block, _join(path, name))
            for name, item in given.items()
        }

    if spec.kind == "block_list":
        if not isinstance(raw, list):
            raise ConfigSchemaError(f"{path}: expected a list, found {_typename(raw)}")
        if not raw:
            raise ConfigSchemaError(f"{path}: is empty. {spec.doc}")
        return [_block(item, spec.block, f"{path}.{i}") for i, item in enumerate(raw)]

    raise ConfigSchemaError(f"{path}: unsupported field kind {spec.kind!r}")


def _block(raw: object, fields: tuple[Field, ...], path: str) -> dict[str, Any]:
    given = _mapping(raw if raw is not None else {}, path)
    known = {f.name: f for f in fields}

    for key in given:
        _reject_credential_key(key, path)
        if key not in known:
            where = f"{path}: " if path else "config: "
            raise ConfigSchemaError(
                f"{where}unknown key {key!r}. An ignored key is a config that "
                f"does not do what it says. Valid keys here: "
                f"{', '.join(sorted(known))}"
            )

    result: dict[str, Any] = {}
    for spec in fields:
        if spec.name in given and given[spec.name] is not None:
            result[spec.name] = _value(given[spec.name], spec, _join(path, spec.name))
        elif spec.required:
            raise _missing(spec, _join(path, spec.name))
        else:
            result[spec.name] = _default_for(spec)
    return result


def _refuse_userinfo(name: str, base_url: str) -> None:
    """Refuse a ``base_url`` that carries a credential in its userinfo.

    ``https://user:key@host`` is a credential written into the config file,
    which :meth:`Config.secret` refuses in the one place it is asked for — "put
    it in a git-ignored .env; never write the value into the config file". The
    same rule, held where the value enters rather than where it is read.

    Refusing here is what makes the rule cheap everywhere else. A ``base_url``
    is interpolated into roughly a dozen operator-facing strings — every runner
    transport error, every availability verdict, ``mcgyvr sources``, the init
    summary — and a credential that cannot be in the value cannot be in any of
    them. Scrubbing each sink instead would have to be got right once per sink
    and again for every sink added later, which is the shape of defect this
    check exists to make impossible rather than to keep catching.
    """
    userinfo = urllib.parse.urlsplit(base_url).netloc.rpartition("@")[0]
    if not userinfo:
        return
    raise ConfigSchemaError(
        f"sources.{name}.base_url: carries credentials in the URL "
        f"({userinfo.split(':')[0]}:...@). A URL is quoted in error messages, "
        f"probe verdicts and `mcgyvr sources`, so a key written here reaches "
        f"logs and terminals that a key in the environment never does. Remove "
        f"the `user:password@` part and name the variable holding it with "
        f"`api_key_env`."
    )


def _cross_validate(data: Mapping[str, Any]) -> None:
    """Reject configs that satisfy the schema but contradict themselves."""
    sources: Mapping[str, Any] = data["sources"]
    if not sources:
        raise ConfigSchemaError(
            "sources: no source is declared. mcgyvr needs at least one "
            "endpoint to dispatch work to."
        )

    for name, block in sources.items():
        _refuse_userinfo(name, str(block["base_url"]))

    seen: set[str] = set()
    for index, tier in enumerate(data["ladder"]["tiers"]):
        name = tier["name"]
        if name in seen:
            raise ConfigSchemaError(
                f"ladder.tiers.{index}.name: {name!r} is used by more than one "
                f"rung. Rung names are how tiers are referred to elsewhere, so "
                f"they have to be unique."
            )
        seen.add(name)
        if tier["source"] not in sources:
            raise ConfigSchemaError(
                f"ladder.tiers.{index}.source: {tier['source']!r} is not a "
                f"declared source. Declared: {', '.join(sorted(sources))}"
            )

    for role in ("orchestrator", "verifier"):
        bound = data[role]["source"]
        if bound is not None and bound not in sources:
            raise ConfigSchemaError(
                f"{role}.source: {bound!r} is not a declared source. "
                f"Declared: {', '.join(sorted(sources))}"
            )

    if data["verifier"]["enabled"] and data["verifier"]["source"] is None:
        raise ConfigSchemaError(
            "verifier.source: required key is not set. Verification is "
            "enabled, so it needs a source to run on — bind one, or set "
            "`verifier.enabled: false` to accept on the deterministic gate "
            "alone."
        )


def named_config_path() -> Path | None:
    """The config path the environment names, or ``None`` if it names none.

    Split out of :func:`config_path` because "somebody chose this path" is a
    fact about the *caller*, not about the file, and it survives the file not
    being there — which is the only moment it matters. A default location with
    nothing in it is a bare install; ``$MCGYVR_CONFIG`` pointing at nothing is
    a variable set ahead of the ``init`` that fills it, or a typo, and the two
    want different sentences. Callers that take a path from a flag already know
    the answer and do not need this.
    """
    override = os.environ.get(CONFIG_PATH_ENV)
    return Path(override).expanduser() if override else None


def user_config_path() -> Path:
    """``~/.mcgyvr/config/mcgyvr.yaml``, expanded against the current HOME."""
    return Path(USER_CONFIG_DIR).expanduser() / CONFIG_FILENAME


def config_path() -> Path:
    """Locate the config file: explicit override, then cwd, then the user dir.

    The user dir is :data:`USER_CONFIG_DIR` and nothing else: the XDG config
    home was the third answer until 2026-09-05, and the owner asked for one
    directory of mcgyvr's own. A path that depends on an environment variable
    only some shells export is a config that is found from one terminal and
    not another, which is the same file in two places as far as an operator
    debugging it is concerned.
    """
    override = named_config_path()
    if override is not None:
        return override
    local = Path.cwd() / CONFIG_FILENAME
    if local.is_file():
        return local
    return user_config_path()


def parse(text: str, path: Path | None = None) -> Config:
    """Validate a config from YAML text."""
    try:
        raw = yaml.load(text, Loader=_StrictLoader)
    except yaml.YAMLError as exc:
        where = f"{path}: " if path else ""
        raise ConfigFileError(f"{where}not valid YAML: {exc}") from exc

    if raw is None:
        raise ConfigSchemaError(
            f"{path or 'config'}: is empty. Run `mcgyvr init` to generate one."
        )

    declared = raw.get("version") if isinstance(raw, dict) else None
    if isinstance(declared, int) and declared != SCHEMA_VERSION:
        raise ConfigSchemaError(
            f"unsupported config version {declared!r} — this build reads "
            f"version {SCHEMA_VERSION}."
        )

    data = _block(raw, SCHEMA, "")
    _cross_validate(data)

    sources = {
        name: Source(
            name=name,
            base_url=block["base_url"],
            api=block["api"],
            max_parallel=block["max_parallel"],
            api_key_env=block["api_key_env"],
            engine=block["engine"],
            image=block["image"],
        )
        for name, block in data["sources"].items()
    }
    ladder = Ladder(
        tiers=tuple(
            Tier(
                name=t["name"],
                source=t["source"],
                model=t["model"],
                max_parallel=t["max_parallel"],
                attempts=t["attempts"],
            )
            for t in data["ladder"]["tiers"]
        ),
        fanout=data["ladder"]["fanout"],
    )
    return Config(path=path, data=data, sources=sources, ladder=ladder)


def _absent_remedy(path: Path | None) -> str:
    """What to do about a config that is not there, given who chose the path.

    Three situations wearing one exception. ``path`` is what the caller named
    on purpose — a ``--config`` flag — or ``None`` when nobody did and
    :func:`load` located the file itself; in that second case
    ``$MCGYVR_CONFIG`` may still have named it, and that is a third answer
    again.

    Nobody named one: both remedies are open and both are said. The variable
    named it: ``mcgyvr init`` writes to exactly that path — ``_init`` resolves
    its destination the same way and its help says so — so a fresh install
    with the documented ``export MCGYVR_CONFIG=...`` already done is one
    command from finished, and answering it with "set the variable" is advice
    to do again what has just been done. A flag named it: the file typed is not
    there, and only a different path helps.
    """
    if path is not None:
        return "Name one that is there."
    if named_config_path() is not None:
        return (
            "`mcgyvr init` writes there: run it to generate one, or "
            "name a file that already exists."
        )
    return (
        f"Run `mcgyvr init` to generate one, or set {CONFIG_PATH_ENV} "
        f"to point at an existing file."
    )


def load(path: Path | None = None) -> Config:
    """Load and validate the config file.

    ``path`` is one the caller was pointed at on purpose — a ``--config`` flag,
    say. ``None`` means nobody named one, and this locates the file rather than
    the caller: that is not a convenience, it is the only way the remedy for a
    file that is not there can be right. Which of ``$MCGYVR_CONFIG``, a flag,
    or nothing at all put this path here is a fact about the *caller*, and a
    caller that resolves the path itself has thrown it away before this
    function can be asked. It was a ``named`` keyword the caller passed
    alongside a resolved path, and four of the five commands that load a config
    never passed it — so each shipped "set ``$MCGYVR_CONFIG``" to operators
    whose ``$MCGYVR_CONFIG`` was the reason they were reading the message.
    """
    chosen = path
    if path is None:
        path = config_path()
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise ConfigMissingError(
            f"no config at {path}. {_absent_remedy(chosen)}"
        ) from exc
    except UnicodeDecodeError as exc:
        # Caught by name, not by family. It is a `ValueError`, so neither
        # `except` below it saw it and it left `load` as a traceback — from a
        # file that is present and unusable, which is the case every caller
        # here already knows how to say something about. A `ConfigFileError`
        # is what "there is a file and this run cannot use it" means.
        raise ConfigFileError(
            f"cannot read {path}: it is not UTF-8 text ({exc})"
        ) from exc
    except OSError as exc:
        raise ConfigFileError(f"cannot read {path}: {exc}") from exc
    return parse(text, path=path)
