"""The single configuration file: its schema, its loader, its failure behaviour.

One file to edit, generated by ``mcgyvr init`` — not a short file. The
ladder is fully configurable, so sources, tier bindings, the orchestrator
and verifier roles, the sandbox, delivery and budgets all live here. It is
YAML rather than JSON because it carries policy, and policy needs comments
to stay hand-editable (ADR-0001, "Known tension").

Three properties are load-bearing and each is enforced here rather than
documented and hoped for:

1. **No silent defaults for things that must be bound.** A default ships
   only when it is a real working value. Anything else is absent, and its
   absence surfaces at the point of use naming the key and how to bind it —
   never as a fallback that makes a misconfiguration look like a bug.
2. **Unknown keys fail.** A typo'd key that is ignored is a config that
   silently does something other than what it says.
3. **Credentials are never values.** The config records only the NAME of
   the environment variable holding each key; the orchestrator process
   resolves it, and a task sandbox never sees it (see ``SECURITY.md``).

``SCHEMA`` below is declarative data, not a set of hand-written checks: it
is what the validator walks and what the config reference is generated
from, so a documented key and a validated key cannot drift apart.

This module only declares and loads. Detecting hardware, proposing
bindings, and writing the file are separate concerns and do not live here.
"""

from __future__ import annotations

import os
import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import yaml

SCHEMA_VERSION = 1
CONFIG_FILENAME = "mcgyvr.yaml"
CONFIG_PATH_ENV = "MCGYVR_CONFIG"


class ConfigError(Exception):
    """Base class for every configuration failure."""


class ConfigFileError(ConfigError):
    """The config file is missing, unreadable, or not parseable as YAML."""


class ConfigSchemaError(ConfigError):
    """The config parsed, but does not satisfy the schema."""


class CredentialInConfigError(ConfigSchemaError):
    """A credential was written into the config as a literal value.

    Distinct from a plain schema error because the remedy is not "fix the
    key" — the secret is now in a file that gets committed, and it has to be
    rotated.
    """


class UnboundValueError(ConfigError):
    """A value the running code needs is not bound.

    Raised at the point of use, never at load: a config that omits an API
    provider is valid, and only becomes a problem if something tries to use
    one.
    """


Kind = Literal[
    "int",
    "str",
    "url",
    "bool",
    "enum",
    "env_name",
    "str_list",
    "block",
    "block_map",
    "block_list",
]


@dataclass(frozen=True)
class Field:
    """One key in the schema, with everything needed to validate and document it.

    ``doc`` has no default on purpose: a key that cannot be explained does
    not belong in a file a stranger is asked to edit.
    """

    name: str
    kind: Kind
    doc: str
    required: bool = False
    default: Any = None
    choices: tuple[str, ...] = ()
    block: tuple[Field, ...] = ()
    min_value: int | None = None
    bind_hint: str = ""


SOURCE_FIELDS: tuple[Field, ...] = (
    Field(
        "base_url",
        "url",
        "Where the source answers, including scheme and port.",
        required=True,
        bind_hint="e.g. http://localhost:11434",
    ),
    Field(
        "api",
        "enum",
        "Wire protocol. `openai` covers vLLM, llama-server, LM Studio and "
        "TGI, so adding a backend is a protocol question, not an "
        "integration.",
        required=True,
        choices=("ollama", "openai"),
    ),
    Field(
        "max_parallel",
        "int",
        "How many requests this source may run at once. Concurrency is "
        "capacity, not a preference: measured, three models ran concurrently "
        "on one card in 23.6 s against ~44 s serial.",
        default=1,
        min_value=1,
    ),
    Field(
        "api_key_env",
        "env_name",
        "NAME of the environment variable holding this source's key. Absent "
        "means the source needs no credential, which is the normal case for "
        "a local backend.",
        bind_hint=(
            "set it to the variable's NAME (e.g. ANTHROPIC_API_KEY), never "
            "the key itself"
        ),
    ),
)

TIER_FIELDS: tuple[Field, ...] = (
    Field(
        "name",
        "str",
        "How this rung is referred to elsewhere — risk floors, routing "
        "policy, telemetry. Conventionally `<locality>_<model>`, e.g. "
        "`local_qwen2.5-coder-7b`, which says what the rung is rather than "
        "where it sits: a positional name silently changes meaning when a "
        "rung is inserted above it. There is no role in the name because a "
        "binding's role is already given by where it sits — this is the "
        "ladder, so it is a worker.",
        required=True,
    ),
    Field(
        "source",
        "str",
        "Which declared source executes this rung. Resolution happens at the "
        "execution seam only — nothing above it knows where work ran.",
        required=True,
    ),
    Field("model", "str", "Model identifier as the source names it.", required=True),
    Field(
        "attempts",
        "int",
        "How many times this rung may be tried before escalation moves on. "
        "The default of 1 is escalate-rather-than-retry: a second attempt "
        "re-runs the same model on the same input, and the figure inherited "
        "from local-ai and not re-verified here (#152) — worker-tier "
        "remediation rescued 2 of 35 failures — says that is usually spend "
        "without a result. Raising it is most "
        "defensible on the dearest rung, which has nowhere to escalate to. A "
        "contract's `limits.attempts` caps this per task; the lower of the "
        "two applies.",
        default=1,
        min_value=1,
    ),
)

LADDER_FIELDS: tuple[Field, ...] = (
    Field(
        "tiers",
        "block_list",
        "The rungs, cheapest first. A higher rung must be measurably better "
        "than the one below or it is not a rung — binding a faster-but-weaker "
        "model above a slower-but-stronger one inverts the ladder and makes "
        "escalation actively harmful.",
        required=True,
        block=TIER_FIELDS,
    ),
    Field(
        "fanout",
        "enum",
        "Whether a batch of contracts spreads across rungs or queues on one. "
        "`none` is today's behaviour: the cheapest rung at or above the "
        "contract's floor, queued behind whoever is already there. `idle` "
        "takes the cheapest such rung that has a free slot — the floor is the "
        "only bound and nothing bounds it above, so when every cheaper rung is "
        "full this reaches a priced api rung rather than wait, which is a "
        "spend decision the knob makes deliberately. `full` spreads across the "
        "eligible rungs regardless of load. It is a knob rather than a "
        "behaviour because the right answer is a property of the machines: two "
        "interchangeable rigs should share a batch, but a throughput rig "
        "feeding an intelligence rig must not — the second is sized to drain "
        "the first's failure tail, and fanning volume onto it eats exactly the "
        "capacity that drain needs.",
        default="none",
        choices=("none", "idle", "full"),
    ),
)

ROLE_FIELDS: tuple[Field, ...] = (
    Field(
        "source",
        "str",
        "Which declared source serves this role. Unset until something needs the role.",
        bind_hint="name one of the sources declared under `sources`",
    ),
    Field(
        "model",
        "str",
        "Model identifier as that source names it.",
        bind_hint="name a model the bound source can serve",
    ),
)

VERIFIER_FIELDS: tuple[Field, ...] = (
    Field(
        "enabled",
        "bool",
        "Model verification of the applied diff, on top of the gate. Off by "
        "default because the deterministic gate is the acceptance bar and a "
        "keyless install is a supported configuration, not a degraded one.",
        default=False,
    ),
    *ROLE_FIELDS,
)

SANDBOX_FIELDS: tuple[Field, ...] = (
    Field(
        "mode",
        "enum",
        "`docker` runs each task in its own container, torn down after. "
        "`tempdir` is the explicitly weaker fallback for installs without "
        "Docker: acceptance commands are arbitrary shell from a contract, "
        "running on someone else's machine.",
        default="docker",
        choices=("docker", "tempdir"),
    ),
    Field(
        "image",
        "str",
        "Base image for task containers. Unset means detect the repository's "
        "stack and build one.",
        bind_hint="name an image tag, or leave unset to let the stack be detected",
    ),
    Field(
        "setup",
        "str_list",
        "Commands run once when the task image is built, before any task.",
        default=(),
    ),
)

DELIVERY_FIELDS: tuple[Field, ...] = (
    Field(
        "mode",
        "enum",
        "How accepted work is handed back. `pull_request` proposes it; "
        "`branch` stops after pushing; `none` leaves it committed locally. "
        "mcgyvr does not silently mutate a working tree it was pointed at.",
        default="pull_request",
        choices=("pull_request", "branch", "none"),
    ),
    Field(
        "token_env",
        "env_name",
        "NAME of the environment variable holding the forge token. Absent "
        "falls back to the ambient `gh` CLI credentials.",
        bind_hint=(
            "set it to the variable's NAME (e.g. GITHUB_TOKEN), never the token itself"
        ),
    ),
)

BUDGET_FIELDS: tuple[Field, ...] = (
    Field(
        "max_escalations",
        "int",
        "How many rungs a task may climb before it is handed back unfinished. "
        "A cheap rung that fails and escalates costs more than starting "
        "higher, so this is a real ceiling, not a retry count.",
        default=1,
        min_value=0,
    ),
    Field(
        "max_attempts",
        "int",
        "Hard ceiling on how many attempts one task may spend in total, "
        "across every rung and every family it climbs. Unset means the "
        "ladder's own budget bounds it — the sum of each reachable rung's "
        "`attempts`, which `mcgyvr pool` prints — so leaving it unset is not "
        "unbounded. Set it when you have raised a rung's `attempts` or "
        "`max_escalations` and want one number that still holds. A decline "
        "costs nothing against it: a rung that stepped aside spent no attempt.",
        min_value=1,
        bind_hint=(
            "set a whole number of attempts, or leave it unset to be bounded "
            "by the ladder's own budget (`mcgyvr pool` prints that number)"
        ),
    ),
    Field(
        "task_timeout_s",
        "int",
        "Wall-clock ceiling for one task, including acceptance commands.",
        default=900,
        min_value=1,
    ),
)

SCHEMA: tuple[Field, ...] = (
    Field(
        "version",
        "int",
        f"Config schema version. Currently {SCHEMA_VERSION}; bumped only by a "
        "breaking change to this file's shape.",
        required=True,
        min_value=1,
    ),
    Field(
        "sources",
        "block_map",
        "Where model work is executed, keyed by a name you choose. A source "
        "is an endpoint with a capacity and a wire protocol — nothing above "
        "the execution seam knows which host or backend served a request.",
        required=True,
        block=SOURCE_FIELDS,
    ),
    Field(
        "ladder",
        "block",
        "The rungs work climbs, and what each is bound to.",
        required=True,
        block=LADDER_FIELDS,
    ),
    Field(
        "orchestrator",
        "block",
        "The role that turns a prompt plus a repository into contracts. Only "
        "used in delegated mode; direct mode authors contracts itself.",
        block=ROLE_FIELDS,
    ),
    Field(
        "verifier",
        "block",
        "The role that reads an applied diff in fresh context.",
        block=VERIFIER_FIELDS,
    ),
    Field("sandbox", "block", "Where a task's commands run.", block=SANDBOX_FIELDS),
    Field(
        "delivery",
        "block",
        "How accepted work gets back to you.",
        block=DELIVERY_FIELDS,
    ),
    Field(
        "budgets",
        "block",
        "The ceilings that bound one task's cost.",
        block=BUDGET_FIELDS,
    ),
)


# Keys that would hold a credential as a value. They are unknown keys and
# would be rejected anyway, but the generic "unknown key" message is the
# wrong advice: what matters is that a secret must not be written here at
# all.
_CREDENTIAL_KEYS = frozenset(
    {
        "access_key",
        "api_key",
        "apikey",
        "auth",
        "auth_token",
        "credential",
        "credentials",
        "key",
        "passwd",
        "password",
        "private_key",
        "secret",
        "secret_key",
        "token",
    }
)

# High-signal credential shapes. This is a tripwire for the obvious cases,
# not a secret scanner — the schema is what actually keeps keys out, by
# giving them nowhere to go.
_CREDENTIAL_VALUE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"^sk-[A-Za-z0-9_\-]{16,}$"),
    re.compile(r"^(ghp|gho|ghs|ghu|ghr)_[A-Za-z0-9]{20,}$"),
    re.compile(r"^github_pat_[A-Za-z0-9_]{20,}$"),
    re.compile(r"^AKIA[0-9A-Z]{16}$"),
    re.compile(r"^xox[baprs]-[A-Za-z0-9\-]{10,}$"),
    re.compile(r"^AIza[0-9A-Za-z_\-]{30,}$"),
)

_ENV_NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass(frozen=True)
class Source:
    """One endpoint work can be dispatched to."""

    name: str
    base_url: str
    api: str
    max_parallel: int
    api_key_env: str | None

    @property
    def requires_credential(self) -> bool:
        return self.api_key_env is not None


@dataclass(frozen=True)
class Tier:
    """One rung of the ladder, bound to a source and a model.

    ``attempts`` is routing policy rather than a property of the binding: it is
    how many times this rung is tried before escalation leaves it, and it lives
    here because policy references a rung by name (ADR-0008). It defaults to 1
    so that the configured behaviour is to escalate rather than retry.
    """

    name: str
    source: str
    model: str
    attempts: int = 1


@dataclass(frozen=True)
class Ladder:
    tiers: tuple[Tier, ...]
    fanout: str = "none"

    def get(self, name: str) -> Tier | None:
        return next((t for t in self.tiers if t.name == name), None)


@dataclass(frozen=True)
class Config:
    """A loaded, validated configuration.

    ``data`` is the validated tree with defaults filled in; ``sources`` and
    ``ladder`` are typed views over the parts that are fully determined.
    Values that are legitimately optional are reached through ``require``
    and ``secret``, which fail at the point of use rather than at load.
    """

    path: Path | None
    data: Mapping[str, Any]
    sources: Mapping[str, Source]
    ladder: Ladder

    @property
    def is_local_only(self) -> bool:
        """Whether every rung runs on a source needing no credential."""
        return not any(
            self.sources[t.source].requires_credential for t in self.ladder.tiers
        )

    def get(self, key: str, default: Any = None) -> Any:
        """Read a dotted key, or ``default`` when it is unbound."""
        try:
            return _dig(self.data, key)
        except KeyError:
            return default

    def require(self, key: str) -> Any:
        """Read a dotted key, failing loud by name when it is not bound.

        This is the point of use. The error names the key and says how to
        bind it, because the alternative — a plausible default — turns a
        misconfiguration into a bug report about something else.
        """
        try:
            value = _dig(self.data, key)
        except KeyError as exc:
            raise UnboundValueError(self._unbound(key)) from exc
        if value is None or value == "" or value == () or value == []:
            raise UnboundValueError(self._unbound(key))
        return value

    def secret(self, key: str) -> str:
        """Resolve the credential whose variable NAME is bound at ``key``.

        Two distinct failures, kept distinct: the config does not say which
        variable holds the key, or it does and that variable is not set.
        """
        var = self.require(key)
        value = os.environ.get(str(var))
        if not value:
            raise UnboundValueError(
                f"environment variable {var} is not set — it is named by "
                f"`{key}`{self._in_file()}. Export it in your shell or put it "
                f"in a git-ignored .env; never write the value into the "
                f"config file."
            )
        return value

    def _unbound(self, key: str) -> str:
        field = field_at(key)
        parts = [f"`{key}` is not bound{self._in_file()}."]
        if field is not None:
            parts.append(field.doc)
            if field.bind_hint:
                parts.append(f"To bind it: {field.bind_hint}.")
        return " ".join(parts)

    def _in_file(self) -> str:
        return f" in {self.path}" if self.path is not None else ""


def field_at(key: str) -> Field | None:
    """Find the schema field a dotted key addresses, if it names one.

    Segments that are a user-chosen map key or a list index are skipped —
    ``sources.local.api_key_env`` and ``ladder.tiers.0.model`` both resolve.
    """
    fields = SCHEMA
    parts = key.split(".")
    index = 0
    while index < len(parts):
        found = next((f for f in fields if f.name == parts[index]), None)
        if found is None:
            return None
        index += 1
        if found.kind == "block":
            fields = found.block
        elif found.kind in ("block_map", "block_list"):
            index += 1  # the caller-chosen name or index
            fields = found.block
        else:
            return found if index == len(parts) else None
        if index == len(parts):
            return found
    return None


def _dig(data: Mapping[str, Any], key: str) -> Any:
    current: Any = data
    for part in key.split("."):
        if isinstance(current, Mapping) and part in current:
            current = current[part]
        elif isinstance(current, Sequence) and not isinstance(current, str):
            try:
                current = current[int(part)]
            except (ValueError, IndexError) as exc:
                raise KeyError(key) from exc
        else:
            raise KeyError(key)
    return current


class _StrictLoader(yaml.SafeLoader):
    """SafeLoader that refuses duplicate keys instead of taking the last one."""


def _no_duplicate_keys(
    loader: yaml.SafeLoader, node: yaml.nodes.MappingNode
) -> dict[Any, Any]:
    mapping: dict[Any, Any] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=True)
        if key in mapping:
            mark = key_node.start_mark
            raise ConfigSchemaError(
                f"duplicate key {key!r} at line {mark.line + 1} — YAML would "
                f"silently keep only the last one, so the file does not mean "
                f"what it looks like it means."
            )
        mapping[key] = loader.construct_object(value_node, deep=True)
    return mapping


_StrictLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _no_duplicate_keys
)


def _typename(value: object) -> str:
    if value is None:
        return "nothing"
    return {
        bool: "a true/false value",
        int: "a number",
        float: "a number",
        str: "text",
        list: "a list",
        dict: "a block of keys",
    }.get(type(value), type(value).__name__)


def _join(path: str, name: str) -> str:
    return f"{path}.{name}" if path else name


def _reject_credential_literal(value: str, path: str) -> None:
    if any(p.match(value) for p in _CREDENTIAL_VALUE_PATTERNS):
        raise CredentialInConfigError(
            f"{path}: this looks like a credential written into the config. "
            f"Credentials are never values here — the config records only the "
            f"NAME of the environment variable holding a key. Rotate this "
            f"secret, then bind it by name."
        )


def _reject_credential_key(name: str, path: str) -> None:
    if name.lower() in _CREDENTIAL_KEYS:
        raise CredentialInConfigError(
            f"{_join(path, name)}: a credential cannot be expressed in the "
            f"config. Name the environment variable that holds it instead "
            f"(`api_key_env` on a source, `token_env` on delivery), and keep "
            f"the value in your environment."
        )


def _mapping(raw: object, path: str) -> dict[str, Any]:
    if not isinstance(raw, dict):
        raise ConfigSchemaError(
            f"{path or 'config'}: expected a block of keys, found {_typename(raw)}"
        )
    for key in raw:
        if not isinstance(key, str):
            raise ConfigSchemaError(
                f"{path or 'config'}: key {key!r} is not text — keys must be names"
            )
    return dict(raw)


def _default_for(spec: Field) -> Any:
    if spec.kind == "block":
        return _block({}, spec.block, "")
    if spec.kind == "block_map":
        return {}
    if spec.kind == "block_list":
        return []
    if spec.kind == "str_list":
        return list(spec.default or ())
    return spec.default


def _missing(spec: Field, path: str) -> ConfigSchemaError:
    parts = [f"{path}: required key is not set.", spec.doc]
    if spec.bind_hint:
        parts.append(f"To bind it: {spec.bind_hint}.")
    return ConfigSchemaError(" ".join(parts))


def _value(raw: object, spec: Field, path: str) -> Any:
    if spec.kind == "int":
        # bool is an int in Python; `max_parallel: true` is not a capacity.
        if not isinstance(raw, int) or isinstance(raw, bool):
            raise ConfigSchemaError(
                f"{path}: expected a number, found {_typename(raw)}"
            )
        if spec.min_value is not None and raw < spec.min_value:
            raise ConfigSchemaError(
                f"{path}: must be at least {spec.min_value}, found {raw}"
            )
        return raw

    if spec.kind == "bool":
        if not isinstance(raw, bool):
            raise ConfigSchemaError(
                f"{path}: expected true or false, found {_typename(raw)}"
            )
        return raw

    if spec.kind in ("str", "url", "enum", "env_name"):
        if not isinstance(raw, str):
            raise ConfigSchemaError(f"{path}: expected text, found {_typename(raw)}")
        value = raw.strip()
        if not value:
            raise ConfigSchemaError(
                f"{path}: is empty. Remove the key or give it a value — an "
                f"empty value is not the same as an unset one."
            )
        _reject_credential_literal(value, path)
        if spec.kind == "enum" and value not in spec.choices:
            raise ConfigSchemaError(
                f"{path}: {value!r} is not a valid value. Valid: "
                f"{', '.join(spec.choices)}"
            )
        if spec.kind == "url" and not value.startswith(("http://", "https://")):
            raise ConfigSchemaError(
                f"{path}: {value!r} is not a URL — it needs a scheme, e.g. "
                f"http://{value}"
            )
        if spec.kind == "env_name" and not _ENV_NAME.match(value):
            raise ConfigSchemaError(
                f"{path}: {value!r} is not an environment variable name. This "
                f"key takes the NAME of the variable holding the value (e.g. "
                f"ANTHROPIC_API_KEY), never the value itself."
            )
        return value

    if spec.kind == "str_list":
        if not isinstance(raw, list):
            raise ConfigSchemaError(f"{path}: expected a list, found {_typename(raw)}")
        out: list[str] = []
        for i, item in enumerate(raw):
            if not isinstance(item, str) or not item.strip():
                raise ConfigSchemaError(
                    f"{path}.{i}: expected text, found {_typename(item)}"
                )
            _reject_credential_literal(item.strip(), f"{path}.{i}")
            out.append(item.strip())
        return out

    if spec.kind == "block":
        return _block(raw, spec.block, path)

    if spec.kind == "block_map":
        given = _mapping(raw, path)
        return {
            name: _block(item, spec.block, _join(path, name))
            for name, item in given.items()
        }

    if spec.kind == "block_list":
        if not isinstance(raw, list):
            raise ConfigSchemaError(f"{path}: expected a list, found {_typename(raw)}")
        if not raw:
            raise ConfigSchemaError(f"{path}: is empty. {spec.doc}")
        return [_block(item, spec.block, f"{path}.{i}") for i, item in enumerate(raw)]

    raise ConfigSchemaError(f"{path}: unsupported field kind {spec.kind!r}")


def _block(raw: object, fields: tuple[Field, ...], path: str) -> dict[str, Any]:
    given = _mapping(raw if raw is not None else {}, path)
    known = {f.name: f for f in fields}

    for key in given:
        _reject_credential_key(key, path)
        if key not in known:
            where = f"{path}: " if path else "config: "
            raise ConfigSchemaError(
                f"{where}unknown key {key!r}. An ignored key is a config that "
                f"does not do what it says. Valid keys here: "
                f"{', '.join(sorted(known))}"
            )

    result: dict[str, Any] = {}
    for spec in fields:
        if spec.name in given and given[spec.name] is not None:
            result[spec.name] = _value(given[spec.name], spec, _join(path, spec.name))
        elif spec.required:
            raise _missing(spec, _join(path, spec.name))
        else:
            result[spec.name] = _default_for(spec)
    return result


def _cross_validate(data: Mapping[str, Any]) -> None:
    """Reject configs that satisfy the schema but contradict themselves."""
    sources: Mapping[str, Any] = data["sources"]
    if not sources:
        raise ConfigSchemaError(
            "sources: no source is declared. mcgyvr needs at least one "
            "endpoint to dispatch work to."
        )

    seen: set[str] = set()
    for index, tier in enumerate(data["ladder"]["tiers"]):
        name = tier["name"]
        if name in seen:
            raise ConfigSchemaError(
                f"ladder.tiers.{index}.name: {name!r} is used by more than one "
                f"rung. Rung names are how tiers are referred to elsewhere, so "
                f"they have to be unique."
            )
        seen.add(name)
        if tier["source"] not in sources:
            raise ConfigSchemaError(
                f"ladder.tiers.{index}.source: {tier['source']!r} is not a "
                f"declared source. Declared: {', '.join(sorted(sources))}"
            )

    for role in ("orchestrator", "verifier"):
        bound = data[role]["source"]
        if bound is not None and bound not in sources:
            raise ConfigSchemaError(
                f"{role}.source: {bound!r} is not a declared source. "
                f"Declared: {', '.join(sorted(sources))}"
            )

    if data["verifier"]["enabled"] and data["verifier"]["source"] is None:
        raise ConfigSchemaError(
            "verifier.source: required key is not set. Verification is "
            "enabled, so it needs a source to run on — bind one, or set "
            "`verifier.enabled: false` to accept on the deterministic gate "
            "alone."
        )


def config_path() -> Path:
    """Locate the config file: explicit override, then cwd, then user config."""
    override = os.environ.get(CONFIG_PATH_ENV)
    if override:
        return Path(override).expanduser()
    local = Path.cwd() / CONFIG_FILENAME
    if local.is_file():
        return local
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg).expanduser() if xdg else Path.home() / ".config"
    return base / "mcgyvr" / "config.yaml"


def parse(text: str, path: Path | None = None) -> Config:
    """Validate a config from YAML text."""
    try:
        raw = yaml.load(text, Loader=_StrictLoader)
    except yaml.YAMLError as exc:
        where = f"{path}: " if path else ""
        raise ConfigFileError(f"{where}not valid YAML: {exc}") from exc

    if raw is None:
        raise ConfigSchemaError(
            f"{path or 'config'}: is empty. Run `mcgyvr init` to generate one."
        )

    declared = raw.get("version") if isinstance(raw, dict) else None
    if isinstance(declared, int) and declared != SCHEMA_VERSION:
        raise ConfigSchemaError(
            f"unsupported config version {declared!r} — this build reads "
            f"version {SCHEMA_VERSION}."
        )

    data = _block(raw, SCHEMA, "")
    _cross_validate(data)

    sources = {
        name: Source(
            name=name,
            base_url=block["base_url"],
            api=block["api"],
            max_parallel=block["max_parallel"],
            api_key_env=block["api_key_env"],
        )
        for name, block in data["sources"].items()
    }
    ladder = Ladder(
        tiers=tuple(
            Tier(
                name=t["name"],
                source=t["source"],
                model=t["model"],
                attempts=t["attempts"],
            )
            for t in data["ladder"]["tiers"]
        ),
        fanout=data["ladder"]["fanout"],
    )
    return Config(path=path, data=data, sources=sources, ladder=ladder)


def load(path: Path | None = None) -> Config:
    """Load and validate the config file."""
    path = path or config_path()
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise ConfigFileError(
            f"no config at {path}. Run `mcgyvr init` to generate one, or set "
            f"{CONFIG_PATH_ENV} to point at an existing file."
        ) from exc
    except OSError as exc:
        raise ConfigFileError(f"cannot read {path}: {exc}") from exc
    return parse(text, path=path)
