"""The `observed` block: captured comprehensively, compared by nothing (#286).

ADR-0027 D7. The properties here are the ones a later reader has to be able to
trust without re-deriving them: every declared field is present, a null carries
a reason, nothing on the way in reaches disk unredacted, and — the one that is
not about content — **nothing reads this file**. That last one is a test rather
than a docstring because it is the property a future lane is most likely to
break by accident, by wiring a guard to a field that is comprehensive precisely
because nobody admitted it.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import types
from pathlib import Path
from typing import Any

import pytest

REPO = Path(__file__).resolve().parent.parent


def _by_path(name: str, path: Path) -> types.ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def observed() -> Any:
    return _by_path("bench_observed", REPO / "tools" / "bench" / "observed.py")


# The two documents, in the shape srv2 (ollama 0.32.5) returned them on
# 2026-08-18 for `qwen2.5-coder:1.5b`, cut down to the keys under test. The
# tokenizer arrays are the real lengths in miniature. Since D5 they are elided
# by NAME, not by length — `MAX_INLINE_ITEMS` is only the backstop for an array
# nobody named — so their sizes no longer straddle a threshold and are simply
# realistic. The size relation the earlier version of this comment described
# stopped being the rule the code applies.
TAGS: dict[str, Any] = {
    "models": [
        {
            "name": "qwen2.5-coder:1.5b",
            "model": "qwen2.5-coder:1.5b",
            "digest": "d7372fd828518a4d",
            "details": {
                "family": "qwen2",
                "parameter_size": "1.5B",
                "quantization_level": "Q4_K_M",
                "context_length": 32768,
            },
        }
    ]
}

SHOW: dict[str, Any] = {
    "details": {"family": "qwen2", "quantization_level": "Q4_K_M"},
    "template": "{{ .Prompt }}",
    "modelfile": (
        '# Modelfile generated by "ollama show"\n'
        "FROM /usr/share/ollama/.ollama/models/blobs/sha256-29d8c98fa6b0\n"
    ),
    "model_info": {
        "general.architecture": "qwen2",
        "qwen2.context_length": 32768,
        "tokenizer.ggml.tokens": [f"t{i}" for i in range(1000)],
        "tokenizer.ggml.pre": "qwen2",
    },
    "tensors": [{"name": "token_embd.weight", "type": "Q6_K", "shape": [1536, 151936]}],
    "capabilities": ["completion", "tools", "insert"],
}


def _endpoint(
    observed: Any,
    monkeypatch: pytest.MonkeyPatch,
    tags: Any,
    show: Any,
    *,
    ps: Any = None,
    models: Any = None,
    version: Any = None,
    server_info: Any = None,
    metrics: str | None = None,
) -> None:
    """A server, without one — routed by URL, through the module's own seams.

    Routed rather than answered flat because the engine is identified from
    *which* calls come back: a fake that returned the same document to
    ``/api/tags`` and ``/v1/models`` would make every arm look like ollama, and
    the dispatch this file exists to test would never run.
    """
    table = {
        "/api/tags": tags,
        "/api/ps": ps,
        "/api/version": version if tags is not None else None,
        "/v1/models": models,
        "/version": version if tags is None else None,
        "/server_info": server_info,
    }

    def get(url: str, *, timeout: float) -> Any:
        for path, answer in table.items():
            if url.endswith(path):
                return answer
        return None

    monkeypatch.setattr(observed.identity, "_get_json", get, raising=True)
    monkeypatch.setattr(
        observed.identity, "_post_json", lambda url, body, *, timeout: show
    )
    monkeypatch.setattr(
        observed, "_get_text", lambda url, *, timeout: metrics, raising=True
    )


# `/api/ps` for a RESIDENT model, in the shape both rigs returned on
# 2026-08-18. `context_length` here is 4096 — ollama's `num_ctx` default —
# against the 32768 trained window `/api/tags` and `/api/show` report.
PS: dict[str, Any] = {
    "models": [
        {
            "name": "qwen2.5-coder:1.5b",
            "model": "qwen2.5-coder:1.5b",
            "size_vram": 1166236712,
            "context_length": 4096,
            "details": {"quantization_level": "Q4_K_M"},
        }
    ]
}

# vLLM 0.26.0, measured on srv1 (1.5B-AWQ, --max-model-len 8192,
# --max-num-seqs 8) and srv2 (7B-AWQ, --max-model-len 16384, --max-num-seqs 16)
# on 2026-08-18. These are cut-down copies of what those servers returned.
VLLM_MODELS: dict[str, Any] = {
    "object": "list",
    "data": [
        {
            "id": "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ",
            "object": "model",
            "owned_by": "vllm",
            "root": "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ",
            "parent": None,
            "max_model_len": 8192,
        }
    ],
}

# `/server_info` exists ONLY under VLLM_SERVER_DEV_MODE=1, and `vllm_config` is
# a Python repr rather than a JSON object — 3,118 characters on srv1. This is
# the head of the real string, which is where all three settings sit.
VLLM_SERVER_INFO: dict[str, Any] = {
    "vllm_config": (
        "model='Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ', speculative_config=None, "
        "dtype=torch.float16, max_seq_len=8192, tensor_parallel_size=1, "
        "quantization=auto_awq, quantization_config=None, enforce_eager=True, "
        "kv_cache_dtype=auto, device_config=cuda, seed=0, "
        "served_model_name=Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ, "
        "enable_prefix_caching=True, enable_chunked_prefill=True"
    ),
    "vllm_env": {"VLLM_ALLOW_LONG_MAX_MODEL_LEN": False},
}

# srv1's real `cache_config_info` labels. `kv_cache_max_concurrency` is the
# value that LOOKS like the answer for `concurrency` and is not — see the test
# that pins the refutation.
VLLM_METRICS = (
    "# HELP vllm:cache_config_info Information of the LLMEngine CacheConfig\n"
    "# TYPE vllm:cache_config_info gauge\n"
    'vllm:cache_config_info{block_size="16",enable_prefix_caching="True",'
    'gpu_memory_utilization="0.85",kv_cache_max_concurrency="16.00390625",'
    'kv_cache_size_tokens="131104"} 1.0\n'
    'vllm:num_requests_running{model_name="Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ"} 0.0\n'
)


# --- the probe set ----------------------------------------------------------


def test_every_declared_field_is_present_and_every_null_states_why(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """D2's three states, on the four fields nothing wrote before this module.

    An **absent** key means the record predates the contract, so a capture made
    from here on must never produce one — including for the fields this rig's
    endpoints do not answer, which is three of the four.
    """
    _endpoint(observed, monkeypatch, TAGS, SHOW)
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")

    for field in observed.PROBE_SET:
        assert field in block, f"{field} is absent, which D2 reads as 'predates'"
    reasons = block[observed.identity.REFUSALS]
    for field in observed.PROBE_SET:
        if block[field] is None:
            assert reasons.get(field), f"{field} is null with no stated reason"
        else:
            assert field not in reasons


def test_quantization_is_answered_because_the_native_surface_answers_it(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The one of the four that is on the surface. Measured: `Q4_K_M` on srv2."""
    _endpoint(observed, monkeypatch, TAGS, SHOW)
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    assert block["quantization"] == "Q4_K_M"


def test_quantization_falls_back_to_the_tags_row(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Both calls carry `details`, and a build that drops one is not a refusal."""
    _endpoint(observed, monkeypatch, TAGS, {"template": "x"})
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    assert block["quantization"] == "Q4_K_M"


def test_the_effective_window_comes_from_api_ps_and_never_from_the_tag(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The measured difference between the trained window and the served one.

    `/api/tags` and `/api/show` both report 32768 — what the model was trained
    with. `/api/ps` reports 4096 — what the loaded instance is actually being
    served with, which is ollama's `num_ctx` default and is what a run gets.
    Measured on srv1 (0.32.4) and srv2 (0.32.5), 2026-08-18. Recording the
    32768 would put a window on disk that no run ever had.
    """
    _endpoint(observed, monkeypatch, TAGS, SHOW, ps=PS)
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")

    assert block["context_length"] == 4096
    assert "context_length" not in block.get(observed.identity.REFUSALS, {})
    native = block[observed.NATIVE]
    assert native["show"]["model_info"]["qwen2.context_length"] == 32768
    assert native["tags"]["models"][0]["details"]["context_length"] == 32768


def test_a_model_that_is_not_resident_refuses_and_says_so(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`/api/ps` lists only what is IN MEMORY, so the answer has a lifetime.

    Observed for real: srv1 answered 4096 and srv2 refused in the same sweep,
    because srv2's five-minute idle timer had already evicted the model. The
    refusal names residency rather than blaming the endpoint, since a capture
    taken while the model is loaded answers the field.
    """
    _endpoint(observed, monkeypatch, TAGS, SHOW, ps={"models": []})
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")

    assert block["context_length"] is None
    reason = block[observed.identity.REFUSALS]["context_length"]
    assert "RESIDENT" in reason and "not loaded" in reason


def test_a_pinned_num_ctx_is_the_effective_window_and_is_recorded(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The other branch: where the Modelfile states it, the endpoint answers."""
    show = {**SHOW, "parameters": 'num_ctx 8192\nstop "<|im_end|>"\n'}
    _endpoint(observed, monkeypatch, TAGS, show)
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    assert block["context_length"] == 8192
    assert "context_length" not in block[observed.identity.REFUSALS]


def test_concurrency_refuses_and_says_what_that_costs_a_reader(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Not on either call at any time — it is the server's OLLAMA_NUM_PARALLEL.

    Recorded as a refusal rather than omitted because it is the term ADR-0027
    needs: greedy is not deterministic under continuous batching, so a run
    without it cannot be read as reproducing even weakly.
    """
    _endpoint(observed, monkeypatch, TAGS, {**SHOW, "parameters": "num_ctx 8192\n"})
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    assert block["concurrency"] is None
    assert "OLLAMA_NUM_PARALLEL" in block[observed.identity.REFUSALS]["concurrency"]


def test_a_server_side_seed_is_observed_and_an_absent_one_is_stated(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Both branches, and a refusal that names where the answer actually is.

    The seed is NOT unobtainable on ollama — it is on `llama-server`'s /slots
    as `params.seed`, measured 4294967295 (llama.cpp's "fresh random seed per
    request") on both rigs. That endpoint binds 127.0.0.1 on the serving host,
    so a capture written by the dispatching client can never reach it. The
    refusal has to say that, or a later reader concludes nobody can know.
    """
    _endpoint(observed, monkeypatch, TAGS, SHOW)
    absent = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    assert absent["seed"] is None
    reason = absent[observed.identity.REFUSALS]["seed"]
    assert "127.0.0.1" in reason and "4294967295" in reason, (
        "a refusal of REACH must not read as a refusal of existence"
    )

    _endpoint(observed, monkeypatch, TAGS, {**SHOW, "parameters": "seed 42\n"})
    pinned = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    assert pinned["seed"] == 42


def test_no_runner_in_this_tree_sends_a_seed() -> None:
    """The half of "observed, never set" that a probe cannot prove.

    Built rather than grepped: what matters is the payload that leaves the
    process, and a payload assembled from a dict is not something a pattern
    over the source can be trusted about.
    """
    from mcgyvr.pool import Endpoint, Protocol
    from mcgyvr.runner import _RUNNERS, Request

    assert set(_RUNNERS) == set(Protocol), "a protocol with no runner is untested here"
    request = Request(prompt="p", max_output_tokens=16, system="s")
    for protocol, runner_class in _RUNNERS.items():
        endpoint = Endpoint(
            source="test",
            base_url="http://test:11434",
            protocol=protocol,
            max_parallel=1,
            credential_env=None,
        )
        payload = runner_class(endpoint)._payload("m", request)
        assert "seed" not in json.dumps(payload), (
            f"{runner_class.__name__} sends a seed. Greedy bypasses the sampler "
            "RNG, and supplying one is a different experiment (#276 item 9) — "
            "`observed.seed` records what the server holds, not what we set."
        )


def test_an_endpoint_that_answers_nothing_still_produces_the_whole_shape(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The degenerate arm.

    "The schema survives a protocol that answers almost nothing" means the file
    has the same keys and says why they are empty — not that it is absent.
    """
    _endpoint(observed, monkeypatch, None, None)
    block = observed.capture("http://srv2:8000", "some-model")

    assert block[observed.ENGINE] == observed.UNREACHABLE
    assert set(observed.PROBE_SET) <= set(block)
    assert all(block[f] is None for f in observed.PROBE_SET)
    reasons = block[observed.identity.REFUSALS]
    assert set(reasons) == set(observed.PROBE_SET)
    assert all("described itself at all" in reason for reason in reasons.values())
    assert block[observed.NATIVE] == {}


# --- the other engine, which answers the other half (#286, vLLM) -------------


def test_a_vllm_is_identified_and_never_read_as_an_ollama(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The engine decides what a refusal means, so it is on the block.

    Identified from what answers rather than from the port: `detect` guesses
    identity from a port because what it needs is the wire protocol, and this
    needs the server.
    """
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        version={"version": "0.11.0"},
        metrics=VLLM_METRICS,
    )
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct")
    assert block[observed.ENGINE] == observed.VLLM
    assert "tags" not in block[observed.NATIVE]


def test_vllm_answers_the_window_ollama_cannot(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`max_model_len` IS the effective window — `--max-model-len` sets it.

    Both engines answer this field, and each from an endpoint the other does not
    have: ollama from `/api/ps` and only while the model is resident, vLLM from
    the model card and unconditionally. Measured 8192 on srv1 and 16384 on srv2,
    matching the flags each was launched with.
    """
    _endpoint(observed, monkeypatch, None, None, models=VLLM_MODELS)
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert block["context_length"] == 8192
    assert "context_length" not in block.get(observed.identity.REFUSALS, {})


def test_vllm_refuses_the_quantization_ollama_answers(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The other half of the trade, and it refuses rather than guessing.

    `--quantization` is a launch flag the server does not report back, so it is
    unobtainable here — which is a different fact from "absent" and is stated
    as such.
    """
    _endpoint(observed, monkeypatch, None, None, models=VLLM_MODELS)
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct")
    assert block["quantization"] is None
    assert "quantization" in block[observed.identity.REFUSALS]


def test_concurrency_refuses_on_vllm_and_never_takes_the_lookalike(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The measured refutation of the substitute that would have been taken.

    `max_num_seqs` — the scheduler's batch width, which is what this field
    means — is on no endpoint of vLLM 0.26.0. Searched exhaustively on
    2026-08-18 across every parameterless GET in the server's own
    `/openapi.json` route table, on both rigs.

    `kv_cache_max_concurrency` is right there in the metrics and looks like the
    answer. It is KV-cache capacity, and it moves OPPOSITE to the flag: srv1
    ran `--max-num-seqs 8` and reported 16.004; srv2 ran 16 and reported 5.314.
    A capture that took it would have recorded a number that gets *smaller* as
    the real concurrency gets larger — which is why this asserts the refusal
    rather than a value.
    """
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        server_info=VLLM_SERVER_INFO,
        metrics=VLLM_METRICS,
    )
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")

    assert block["concurrency"] is None
    reason = block[observed.identity.REFUSALS]["concurrency"]
    assert "max_num_seqs" in reason
    assert "16.004" in reason and "5.314" in reason, (
        "the refusal must carry the measurement that refutes the lookalike, "
        "or the next lane re-derives it from the same tempting label"
    )
    # Captured raw regardless, so a later question is answerable off the run.
    assert "kv_cache_max_concurrency" in block[observed.NATIVE]["metrics"]


def test_dev_mode_is_what_makes_quantization_and_seed_observable(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The single biggest lever on how much of the probe set a vLLM answers.

    `/server_info` is gated behind `VLLM_SERVER_DEV_MODE=1`. With it, three of
    four fields are answered (measured `quantization=auto_awq`, `seed=0`,
    `max_seq_len=8192` on srv1 and 16384 on srv2). Without it, one is — and the
    refusals name the flag, so a reader learns the field is a fact about how
    the server was started rather than a limit of what vLLM can say.
    """
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        server_info=VLLM_SERVER_INFO,
    )
    on = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert on["quantization"] == "auto_awq"
    assert on["seed"] == 0

    _endpoint(observed, monkeypatch, None, None, models=VLLM_MODELS)
    off = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert off["quantization"] is None
    assert off["seed"] is None
    reasons = off[observed.identity.REFUSALS]
    assert "VLLM_SERVER_DEV_MODE=1" in reasons["quantization"]
    assert "VLLM_SERVER_DEV_MODE=1" in reasons["seed"]
    # The window survives dev mode being off: /v1/models carries it either way.
    assert off["context_length"] == 8192


def test_an_unrecorded_seed_on_vllm_is_a_set_seed(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Measured: vLLM 0.26.0 defaults to `seed=0`, not to none.

    "Observed, never set" is a statement about what this tree DISPATCHES. It is
    not a statement about the server, and on this engine the server has one
    whether anybody asked for it — so a vLLM run whose seed went unrecorded was
    seeded, and the refusal has to say that rather than implying no seed exists.
    """
    _endpoint(
        observed,
        monkeypatch,
        None,
        None,
        models=VLLM_MODELS,
        server_info=VLLM_SERVER_INFO,
    )
    block = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert block["seed"] == 0

    _endpoint(observed, monkeypatch, None, None, models=VLLM_MODELS)
    off = observed.capture("http://rig:8000", "Qwen/Qwen2.5-Coder-1.5B-Instruct-AWQ")
    assert "defaults to" in off[observed.identity.REFUSALS]["seed"]


def test_a_plain_openai_server_is_not_called_a_vllm(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """llama-server, LM Studio and TGI land here, and the block says so."""
    models = {"object": "list", "data": [{"id": "m", "object": "model"}]}
    _endpoint(observed, monkeypatch, None, None, models=models)
    block = observed.capture("http://rig:8080", "m")
    assert block[observed.ENGINE] == observed.OPENAI_COMPATIBLE
    assert block["context_length"] is None
    assert all(block[f] is None for f in observed.PROBE_SET)


def test_two_unmatched_cards_refuse_rather_than_pick_one(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Guessing which card the dispatch used is the substitute D2 forbids.

    One card and no id match is a different case: a served model's id is often
    the path it was loaded from rather than the name a config calls it, and
    there is nothing to be wrong about.
    """
    two = {
        "object": "list",
        "data": [
            {"id": "a", "owned_by": "vllm", "max_model_len": 4096},
            {"id": "b", "owned_by": "vllm", "max_model_len": 32768},
        ],
    }
    _endpoint(observed, monkeypatch, None, None, models=two)
    assert observed.capture("http://rig:8000", "c")["context_length"] is None

    one = {"object": "list", "data": [{"id": "a", "max_model_len": 4096}]}
    _endpoint(observed, monkeypatch, None, None, models=one)
    assert observed.capture("http://rig:8000", "c")["context_length"] == 4096


def test_every_engine_says_whether_it_has_been_run_live(observed: Any) -> None:
    """ADR-0033's convention: the contingency lives where the code is.

    The ollama arm was built against srv2 and its docstring numbers are
    measurements. The vLLM arm was built from documentation because no vLLM was
    reachable. That difference is a fact about how far the module can be
    trusted, so it is declared per engine — and a third arm cannot arrive
    unmarked, because this fails if one does.
    """
    for engine in observed.ENGINES:
        marked = (engine in observed.VERIFIED_LIVE) + (engine in observed.UNVERIFIED)
        assert marked == 1, (
            f"{engine!r} is in neither VERIFIED_LIVE nor UNVERIFIED, or in both. "
            "Say whether this module's shapes for it have been exercised "
            "against a live endpoint — a documented shape and a measured one "
            "are not the same evidence."
        )
    for engine in (observed.OLLAMA, observed.VLLM):
        assert engine in observed.VERIFIED_LIVE, (
            f"{engine} was run against a live server on 2026-08-18 and every "
            "number this module states for it is a measurement; demoting it "
            "means deleting that evidence, not just moving a key."
        )


# --- redaction, on capture and before write ---------------------------------


def test_a_planted_secret_never_reaches_disk(
    observed: Any, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A comprehensive capture of a server's self-description is the risk.

    ``run.json`` holds one URL that one call redacts. This holds a licence, a
    generated Modelfile and a template, any of which a serving host can have
    edited. The fixtures are assembled at runtime rather than written as
    literals: a secret-shaped literal in a tracked file is rejected by GitHub's
    push protection and flagged by this repo's own scanner, and the reassembled
    string exercises the scrub identically.
    """
    token = "ghp_" + "a" * 36
    key_id = "AKIA" + "B" * 16
    credentialed = "https://someone:hunter2@registry.example.com/qwen"
    show = {
        **SHOW,
        "license": f"contact {token} for support",
        "modelfile": f"FROM {credentialed}\n# pulled with {key_id}\n",
        "system": "You are Qwen.",
    }
    _endpoint(observed, monkeypatch, TAGS, show)

    written = observed.write(tmp_path, "http://srv2:11434", "qwen2.5-coder:1.5b")
    assert written is not None
    text = written.read_text(encoding="utf-8")

    for secret in (token, key_id, "hunter2", "someone:hunter2"):
        assert secret not in text, f"{secret!r} reached disk"
    # Redacted, not deleted: the reader still learns a registry was involved.
    assert "registry.example.com" in text


def test_a_home_directory_prefix_is_reduced_and_the_blob_digest_is_kept(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The measured shape, from srv2: the Modelfile's FROM line is a host path.

    On a home-directory install that path names a user, which is what goes; the
    blob filename under it is `sha256-<hex>`, which is the one piece of weights
    identity the native surface exposes and which stays.
    """
    blob = "/home/adar/.ollama/models/blobs/sha256-29d8c98fa6b0"
    _endpoint(observed, monkeypatch, TAGS, {**SHOW, "modelfile": f"FROM {blob}\n"})
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")

    modelfile = block[observed.NATIVE]["show"]["modelfile"]
    assert "/home/adar/" not in modelfile
    assert "/home/<redacted>/.ollama/models/blobs/sha256-29d8c98fa6b0" in modelfile


def test_redaction_reaches_a_string_nested_anywhere(observed: Any) -> None:
    """The risk is not at the top level — the Modelfile is one string in one key."""
    token = "xoxb-" + "1" * 20
    scrubbed = observed.scrub({"a": [{"b": {"c": [f"see {token}"]}}]})
    assert token not in json.dumps(scrubbed)


# --- comprehensive, without copying 7.7 MB into every run directory ----------


def test_a_long_array_is_recorded_as_its_count_and_its_digest(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Measured: the raw `/api/show` document for the 1.5B is 7.7 MB of JSON.

    Essentially all of it is three tokenizer arrays. Nothing a reader can act on
    is lost — the digest is :func:`identity.digest`, the same convention
    ``run.json`` uses, so an elided array joins to ``vocabulary_sha256`` there
    without rehashing anything. Proven here rather than asserted: the two
    digests are computed by the two modules over the same list.
    """
    _endpoint(observed, monkeypatch, TAGS, SHOW)
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    info = block[observed.NATIVE]["show"]["model_info"]

    tokens = info["tokenizer.ggml.tokens"]
    assert tokens[observed.ELIDED] is True
    assert tokens["count"] == 1000
    assert tokens["sha256"] == observed.identity.digest(
        SHOW["model_info"]["tokenizer.ggml.tokens"]
    )
    # Under the threshold, so it stays as it was — a summary of a 1-row list
    # would be less information, not more.
    assert block[observed.NATIVE]["show"]["tensors"] == SHOW["tensors"]


def test_the_elided_digest_is_the_one_run_json_records(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """The join key claim, checked against `probe_model` rather than restated."""
    _endpoint(observed, monkeypatch, TAGS, SHOW)
    fields, _ = observed.identity.probe_model("http://srv2:11434", "qwen2.5-coder:1.5b")
    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    tokens = block[observed.NATIVE]["show"]["model_info"]["tokenizer.ggml.tokens"]
    assert tokens["sha256"] == fields["vocabulary_sha256"]


# --- one capture per directory ----------------------------------------------


def test_a_resume_keeps_the_capture_the_directory_was_opened_with(
    observed: Any, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """Overwriting would lose the only record of what the endpoint said then.

    This block is compared by nothing, so it cannot refuse a resume — and a
    resume against a materially different server is refused by ``run.json``'s
    keyed drift, which is where a refusal belongs.
    """
    _endpoint(observed, monkeypatch, TAGS, SHOW)
    first = observed.write(tmp_path, "http://srv2:11434", "qwen2.5-coder:1.5b")
    assert first is not None
    before = first.read_text(encoding="utf-8")

    _endpoint(observed, monkeypatch, TAGS, {**SHOW, "details": {"family": "other"}})
    assert observed.write(tmp_path, "http://srv2:11434", "qwen2.5-coder:1.5b") is None
    assert first.read_text(encoding="utf-8") == before


def test_a_probe_that_cannot_reach_anything_still_writes(
    observed: Any, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A capture that threw would be the worst of both: no rows AND no record."""

    def boom(*args: Any, **kwargs: Any) -> Any:
        raise AssertionError("the fetchers swallow their own failures")

    monkeypatch.setattr(observed.identity, "_get_json", boom)
    monkeypatch.setattr(observed.identity, "_post_json", boom)
    written = observed.write(tmp_path / "fresh", "http://nothing:1", "m")
    assert written is not None and written.is_file()


# --- nothing reads it -------------------------------------------------------

#: Where the name may appear. The writer, the contract module that explains the
#: state its four fields are now in, and this file. The two runner call sites go
#: through `observed_module.write` and never name the file, which is why they
#: are not here.
NAMES_THE_FILE = {
    "tools/bench/observed.py",
    "tools/bench/identity.py",
    "tests/test_bench_observed.py",
}


def test_nothing_outside_the_writer_names_the_file() -> None:
    """The acceptance property that is about the guard path, not the content.

    A field in this block is comprehensive *because* nobody admitted it. Wiring
    a guard to one would be a comparison on an unadmitted field — the failure
    ADR-0027 D7 separates the two blocks to prevent — so the check is that the
    name does not spread, and the allow-list above is the thing a future lane
    has to argue with.
    """
    found = subprocess.run(
        ["git", "grep", "-l", "observed.json", "--", "src/", "tools/", "tests/"],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    named = {line for line in found.stdout.splitlines() if line}
    assert named <= NAMES_THE_FILE, (
        f"{sorted(named - NAMES_THE_FILE)} name observed.json. Nothing reads "
        "this block for comparison (ADR-0027 D7): a field in it is "
        "comprehensive because nobody admitted it, and promotion into "
        "identity.KEY is the owner's."
    )


def test_the_contract_module_records_the_landed_state(observed: Any) -> None:
    """#286's item 7: the four say what is true now, and did not move to #276's.

    `AWAITING_ADMISSION` means "#276's rule has not admitted it". #276's rule is
    not these fields' promotion path — D7 is — so they get their own reason
    rather than being folded into a queue they are not in.
    """
    identity = observed.identity
    for field in observed.PROBE_SET:
        assert identity.PENDING_REASON[field] == identity.CAPTURED_IN_OBSERVED
        assert field in identity.RECORDED
        assert field not in identity.KEY
    assert not hasattr(identity, "AWAITING_PROBE_SET"), (
        "the third state is gone: nothing in the repository is waiting on a "
        "writer for these four any more."
    )


# --- what the review found, pinned so it cannot come back -------------------


def test_a_base_url_that_already_ends_in_v1_is_not_doubled(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`https://host/v1` is the documented spelling, and it was probed at /v1/v1.

    `tools/bundle/worker.example.json` documents `base_url` with `/v1` on it,
    because every hosted provider prints its endpoint that way — and
    `runner._url_for` exists precisely to absorb it. This module concatenated
    instead, so a healthy server 404'd on every probe and was recorded as
    "nothing there described itself at all".
    """
    asked: list[str] = []

    def get(url: str, *, timeout: float) -> Any:
        asked.append(url)
        return None

    monkeypatch.setattr(observed.identity, "_get_json", get, raising=True)
    monkeypatch.setattr(
        observed.identity, "_post_json", lambda url, body, *, timeout: None
    )
    monkeypatch.setattr(observed, "_get_text", lambda url, *, timeout: None)
    observed.capture("https://api.example.com/v1", "m")

    assert "https://api.example.com/v1/models" in asked
    assert not [url for url in asked if "/v1/v1/" in url]

    # The doubling check above passes even with the bug it was written for:
    # /v1/models is the one path the old rule handled. The six root-level
    # entries in VLLM_READS are where it went wrong, so name them.
    for path in ("/version", "/server_info", "/load", "/is_sleeping"):
        assert f"https://api.example.com{path}" in asked, path
        assert f"https://api.example.com/v1{path}" not in asked, path


def test_a_capture_never_raises_however_bad_the_server_text_is(
    observed: Any, monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """`bundle.redact` reads `urlsplit(...).port`, which RAISES on a bad port.

    Fine for the one URL `run.json` holds; not fine over every string a server
    sent. `record_run` calls the writer after `run.json` is already on disk, so
    an exception here meant a traceback and zero rows — the exact "worst of
    both" the docstring promises to avoid. An unparseable candidate is redacted
    wholesale, because it cannot be shown to be safe.
    """
    hostile = {
        "details": {},
        "modelfile": "FROM registry://u:p@host:99999/blob\n",
        "license": "see ftp://a:b@[unbalanced/x",
    }
    _endpoint(observed, monkeypatch, TAGS, hostile, ps=PS)

    block = observed.capture("http://srv2:11434", "qwen2.5-coder:1.5b")
    text = json.dumps(block)
    assert "99999" not in text and "u:p@" not in text

    # And the writer is belt-and-braces: even a capture that somehow throws must
    # leave a file rather than kill the sweep.
    monkeypatch.setattr(
        observed, "capture", lambda *a, **k: (_ for _ in ()).throw(RuntimeError("boom"))
    )
    written = observed.write(tmp_path, "http://srv2:11434", "qwen2.5-coder:1.5b")
    assert written is not None
    recorded = json.loads(written.read_text())[observed.CAPTURES][observed.AT_OPEN][
        observed.NATIVE_SOURCE
    ]
    assert "boom" in recorded[observed.identity.REFUSALS]["seed"]


def test_a_non_vllm_server_is_never_told_vllm_facts_about_itself(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A null must carry a TRUE reason, and these reasons are vLLM measurements.

    The realistic path is not a hypothetical: an ollama whose `/api/*` calls
    fail transiently falls through to the served arm — ollama does serve
    `/v1/models` — is identified as `openai-compatible`, and would have had
    `/server_info`, `VLLM_SERVER_DEV_MODE=1` and "vLLM 0.26.0 defaults to
    seed=0" written to its disk as the stated reasons for its nulls.
    """
    plain = {"object": "list", "data": [{"id": "m", "object": "model"}]}
    _endpoint(observed, monkeypatch, None, None, models=plain)
    block = observed.capture("http://rig:8080", "m")

    assert block[observed.ENGINE] == observed.OPENAI_COMPATIBLE
    reasons = block[observed.identity.REFUSALS]
    for field, reason in reasons.items():
        for claim in ("VLLM_SERVER_DEV_MODE", "/server_info", "vLLM 0.26.0"):
            assert claim not in reason, f"{field} asserts {claim!r} about a non-vLLM"
    assert all(
        "nothing here has been measured against it" in r for r in reasons.values()
    )


def test_the_long_timeout_is_spent_only_on_the_call_that_earned_it(
    observed: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A dozen probes at the /api/show budget put six minutes before a sweep.

    `CAPTURE_TIMEOUT_S` exists for one call — `/api/show` with `verbose`, which
    returns the tokenizer arrays. Everything else returns kilobytes, and this
    capture runs immediately before the first draw.
    """
    seen: list[tuple[str, float]] = []

    def note_get(url: str, *, timeout: float) -> None:
        seen.append((url, timeout))
        return None

    def note_post(url: str, body: dict[str, Any], *, timeout: float) -> None:
        seen.append((url, timeout))
        return None

    monkeypatch.setattr(observed.identity, "_get_json", note_get, raising=True)
    monkeypatch.setattr(observed.identity, "_post_json", note_post)
    monkeypatch.setattr(observed, "_get_text", note_get, raising=True)
    observed.capture("http://srv2:11434", "m")

    long_calls = [url for url, timeout in seen if timeout >= observed.CAPTURE_TIMEOUT_S]
    assert long_calls == ["http://srv2:11434/api/show"]
    assert all(
        timeout == observed.DISCOVERY_TIMEOUT_S
        for url, timeout in seen
        if url != "http://srv2:11434/api/show"
    )


# --------------------------------------------------------------------------
# #350: the width the record already held, and the width only the client knows.
#
# `concurrency` in PROBE_SET is refused on both engines, correctly — it is on no
# network surface either serves. The ollama refusal ends by naming where the
# answer is, `tools/bench/serving/`, and the `host` block written beside it in
# the same file is produced by that module with that access. These checks hold
# the meeting point: the number reaches the record, the native refusal is left
# exactly as it was, and the two bounds on the realised batch stay two fields.
# --------------------------------------------------------------------------


@pytest.fixture(scope="module")
def pin() -> Any:
    return _by_path("serving_pin", REPO / "tools" / "bench" / "serving" / "pin.py")


def test_the_served_width_is_read_off_the_host_config(pin: Any) -> None:
    """`-np` reaches the record under a name that does not name an engine."""
    reading = pin.width("ollama", "srv1", {"semantic": {"n_parallel": 2}}, None)
    assert reading["value"] == 2
    assert reading["source"] == "host:n_parallel"
    assert "refused" not in reading


def test_two_host_sources_that_disagree_about_the_width_are_refused(
    pin: Any,
) -> None:
    """The flag and the slot count must agree; resolving them would pick one.

    `vllm.declared_slots` already applies this rule to its own pair. A width is
    a fact about the running server, and two contradictory readings of it mean
    the thing being described is not what one of them describes.
    """
    reading = pin.width(
        "ollama", "srv1", {"semantic": {"n_parallel": 2, "total_slots": 1}}, None
    )
    assert reading["value"] is None
    assert "2" in reading["refused"] and "1" in reading["refused"]


def test_a_config_with_no_width_refuses_with_the_config_s_own_reason(
    pin: Any,
) -> None:
    """A refusal that drops the cause underneath it is a refusal twice over."""
    reading = pin.width("ollama", "srv1", {"refused": "no model is resident"}, None)
    assert reading["value"] is None
    assert "no model is resident" in reading["refused"]


def test_the_vllm_width_comes_from_the_launcher_read_not_from_the_wire(
    pin: Any,
) -> None:
    """`--max-num-seqs` is in argv or in the container's Cmd, and nowhere else.

    A server launched at 8 reports `kv_cache_max_concurrency` 16.004, so the
    lookalike moves opposite to the flag and is never substituted. This asserts
    the value arrives from `launched_width` and carries where it was found.
    """

    class _Backend:
        @staticmethod
        def launched_width(host: str) -> dict[str, Any]:
            return {"value": 8, "source": "process"}

    reading = pin.width("vllm", "srv1", {}, _Backend)
    assert reading == {"value": 8, "source": "host:process"}


def test_a_vllm_host_that_will_not_say_its_width_refuses_with_a_reason(
    pin: Any,
) -> None:
    class _Backend:
        @staticmethod
        def launched_width(host: str) -> dict[str, Any]:
            return {"value": None, "source": None}

    reading = pin.width("vllm", "srv1", {}, _Backend)
    assert reading["value"] is None
    assert "max-num-seqs" in reading["refused"]


def test_a_host_with_no_serving_process_still_carries_the_width_key(
    pin: Any, monkeypatch: pytest.MonkeyPatch
) -> None:
    """An ABSENT key means the record predates the contract (ADR-0027 D2).

    The no-process path returns early, and that early return is exactly where a
    key quietly stops being written for one branch of one engine.
    """
    monkeypatch.setattr(
        pin, "same_machine", lambda host, endpoint: {"held": True}, raising=True
    )
    monkeypatch.setattr(
        pin, "instance", lambda host, pattern: {"present": False}, raising=True
    )
    block = pin.host_block("http://srv1:11434")
    assert block["width"]["value"] is None
    assert block["width"]["refused"]


def test_the_served_width_reaches_the_record_the_native_block_refused(
    observed: Any,
) -> None:
    """The number the record already held, in the field declared for it."""
    resolved = observed.resolve({"width": {"value": 2, "source": "host:n_parallel"}}, 1)
    assert resolved[observed.SERVED_WIDTH]["value"] == 2
    assert resolved[observed.DISPATCH_MAX_PARALLEL]["value"] == 1


def test_the_two_widths_are_two_fields_and_neither_stands_in_for_the_other(
    observed: Any,
) -> None:
    """A server width of 4 dispatched at 1 must read as 4 and 1, never as one.

    This is ADR-0040's rule carried across: a per-process figure is not the
    card, and the width a server was started at is not the width a client used.
    """
    resolved = observed.resolve({"width": {"value": 4, "source": "host:n_parallel"}}, 1)
    assert resolved[observed.SERVED_WIDTH]["value"] == 4
    assert resolved[observed.DISPATCH_MAX_PARALLEL]["value"] == 1
    assert observed.SERVED_WIDTH != observed.DISPATCH_MAX_PARALLEL


def test_no_host_block_leaves_the_served_width_null_with_a_reason(
    observed: Any,
) -> None:
    resolved = observed.resolve({}, 1)
    served = resolved[observed.SERVED_WIDTH]
    assert served["value"] is None
    assert served[observed.identity.REFUSALS]


def test_a_runner_that_passes_no_dispatch_width_is_recorded_as_a_refusal(
    observed: Any,
) -> None:
    """Not a zero and not a one. The default must not look like a measurement."""
    resolved = observed.resolve({"width": {"value": 2}}, None)
    dispatch = resolved[observed.DISPATCH_MAX_PARALLEL]
    assert dispatch["value"] is None
    assert dispatch[observed.identity.REFUSALS]


def test_the_resolved_block_never_writes_into_the_native_block(
    observed: Any, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A host reading under the `native` label destroys the file's one axis.

    The sources exist so a reader can tell what kind of evidence a number is.
    A width that arrived over ssh must not appear inside the block that means
    "what the endpoint said about itself".
    """
    monkeypatch.setattr(
        observed,
        "capture",
        lambda endpoint, model, timeout=0.0: {
            "endpoint": endpoint,
            "model": model,
            "concurrency": None,
            observed.identity.REFUSALS: {"concurrency": "not on any endpoint"},
        },
        raising=True,
    )
    observed.write(
        tmp_path,
        "http://srv1:11434",
        "m",
        host={"width": {"value": 2, "source": "host:n_parallel"}},
        dispatch_max_parallel=1,
    )
    written = json.loads((tmp_path / observed.OBSERVED_FILE).read_text())
    capture = written[observed.CAPTURES][observed.AT_OPEN]
    native = capture[observed.NATIVE_SOURCE]
    assert native["concurrency"] is None
    assert native[observed.identity.REFUSALS]["concurrency"]
    assert capture[observed.RESOLVED_SOURCE][observed.SERVED_WIDTH]["value"] == 2


@pytest.mark.parametrize("rig", ["tools/breadth/measure.py", "tools/bundle/measure.py"])
def test_both_runners_pass_the_width_they_dispatched_at(rig: str) -> None:
    """The one half of the pair no probe can recover.

    A server cannot see how many requests a client chose to keep in flight, so
    if the call site does not say it, nothing does — and the field would read
    `null` on every run while the runner knew the answer the whole time. Held
    against the source rather than a captured file because that is where it
    would be dropped.
    """
    source = (REPO / rig).read_text(encoding="utf-8")
    assert "dispatch_max_parallel=worker.as_endpoint().max_parallel" in source
